/* ─────────────────────────────────────────────────────────────
   VIETNAM TRIP — single source of truth.
   Everything (day cards, places grid, map pins, stays) renders
   from this object. Add a place once and it appears everywhere.

   Coordinates: landmarks are accurate; small shops/cafes are
   approximate (approx:true) — nudge them if a pin is off.
   ───────────────────────────────────────────────────────────── */
const TRIP = {
  meta: {
    title: "Vietnam",
    travelers: "Don & Katelyn",
    start: "2026-06-21",
    end:   "2026-07-02",
    updated: "Jun 7, 2026",
  },

  // city id -> palette colour
  cities: [
    { id: "hanoi",  name: "Hanoi",       emoji: "🇻🇳", color: "pink",  nights: "2 nights", lat: 21.0285, lng: 105.8542 },
    { id: "halong", name: "Ha Long Bay", emoji: "🚢", color: "blush", nights: "1 night",  lat: 20.9101, lng: 107.1839 },
    { id: "hoian",  name: "Hoi An",      emoji: "🏮", color: "sage",  nights: "3 nights", lat: 15.8801, lng: 108.3380 },
    { id: "danang", name: "Da Nang",     emoji: "🏖️", color: "lemon", nights: "2 nights", lat: 16.0544, lng: 108.2022 },
    { id: "hcmc",   name: "HCMC",        emoji: "🏙️", color: "lilac", nights: "3 nights", lat: 10.7769, lng: 106.7009 },
  ],

  stats: [
    { num: "11",    label: "Days",   color: "pink"  },
    { num: "5",     label: "Cities", color: "lemon" },
    { num: "5",     label: "Stays",  color: "sage"  },
    { num: "1,700", label: "km",     color: "lilac" },
  ],

  flights: {
    ref: "8MXDM6", airline: "Qatar Airways",
    outbound: { label: "Outbound", airline: "20 Jun · JNB 12:40 → DOH", route: "Doha → Hanoi", time: "Arrive HAN 13:25 (21 Jun)" },
    domestic: { label: "Domestic", airline: "24 Jun · HAN 17:25 → DAD 18:50", route: "Hanoi → Da Nang", time: "VN 187 · Vietnam Airlines · 1h25m" },
    inbound:  { label: "Return",   airline: "2 Jul · SGN 20:00 → DOH",  route: "Doha → Johannesburg", time: "Arrive JNB 09:35 (3 Jul)" },
    note: "~R16,462 pp · Qatar booking ref 8MXDM6",
  },

  // ── STAYS ──
  stays: [
    { name: "La Passion Premium Cau Go", city: "hanoi",  loc: "Hanoi — Old Quarter",
      dates: "Sun 21 Jun – Tue 23 Jun · 2 nights", confirm: "5963820548", phone: "+84886087576",
      lat: 21.0322, lng: 105.8541, est: "R3,300", nights: "2", approx: false },
    { name: "Mon Cheri Cruises", city: "halong", loc: "Ha Long Bay",
      dates: "Tue 23 Jun – Wed 24 Jun · 1 night", confirm: "6223585718", phone: "+84946982299",
      lat: 20.9101, lng: 107.0700, est: "~R5,500", nights: "1 (cruise)", approx: true },
    { name: "Hotel Royal Hoi An, Danang", city: "hoian", loc: "Hoi An",
      dates: "Wed 24 Jun – Sat 27 Jun · 3 nights", confirm: "5760294192", phone: "+842353950777",
      lat: 15.8835, lng: 108.3290, est: "~R6,000", nights: "3", approx: true },
    { name: "Chicland Boutique Danang Beach Hotel", city: "danang", loc: "Da Nang — My Khe Beach",
      dates: "Sat 27 Jun – Mon 29 Jun · 2 nights", confirm: "6288175813", phone: "+842362232222",
      lat: 16.0556, lng: 108.2455, est: "~R3,600", nights: "2", approx: false },
    { name: "ANIMA Boutique Hotel", city: "hcmc", loc: "HCMC — District 1",
      dates: "Mon 29 Jun – Thu 2 Jul · 3 nights", confirm: "6083452364", phone: "+84833881010",
      lat: 10.7690, lng: 106.6940, est: "~R6,900", nights: "3", approx: true },
  ],
  budgetTotal: "~R25,300",
  budgetNote: "All 5 stays confirmed on Booking.com. Estimates based on typical rates.",

  // ── DAYS ──
  days: [
    { n: 1, title: "Arrival in Hanoi", date: "Sun 21 Jun", iso: "2026-06-21", city: "hanoi",
      tags: [["Half day","pink"],["Matcha","sage"],["Food","blush"]],
      cols: [
        { h: "Afternoon — arrival", items: [
          "Land HAN 13:25 → transfer to the Old Quarter, check in (La Passion Premium Cau Go, conf: 5963820548)",
          "? Artisan Matcha Slow Bar (Long Bien) — drop bags & head straight there, closes 17:00. Skip if the flight's late or you're wiped — you'll still get Nagocha tomorrow.",
          "Hoan Kiem Lake + Ngoc Son Temple (temple closes 18:00)",
          "⭐ Cafe Giang — the original egg coffee since 1946 (open late, so flexible)",
        ]},
        { h: "Evening — Old Quarter", items: [
          "⭐ Street food crawl — Ta Hien & Nguyen Trung Truc",
          "Bia Hoi Corner — 25c draught beer on plastic stools",
          "🌟 Old Quarter Night Market — open tonight (Fri–Sun), Hang Dao → Dong Xuan",
          "? Water puppets — Thang Long Theatre by the lake (the original venue; or save it for Saigon)",
        ]},
      ],
      stay: "La Passion Premium Cau Go",
      foot: ["🌧️ Rainy backup: Cafe Giang → Dong Xuan covered market", "Loose plan — grab what you fancy, drop the rest"] },

    { n: 2, title: "Hanoi — City Sweep & West Lake Sunset", date: "Mon 22 Jun", iso: "2026-06-22", city: "hanoi",
      tags: [["History","pink"],["Shopping","lemon"],["Matcha","sage"]],
      cols: [
        { h: "Morning — Dong Da / Ba Dinh (west)", items: [
          "✅ Temple of Literature — Vietnam's oldest university (open Mon)",
          "? One Pillar Pagoda + Ba Dinh Square — grounds only (Mausoleum & HCM Museum closed Mon)",
          "⭐ The Raw Compound — 20+ local streetwear brands, 180 La Thanh",
          "The Matcha Space — quick matcha pop-in, right by Raw Compound",
        ]},
        { h: "Lunch", items: [
          "⭐ Bún chả Hương Liên — the Obama–Bourdain bun cha (a lunch dish; open till 20:00)",
        ]},
        { h: "Afternoon — central + Old Quarter", items: [
          "🌟 Hoa Lo Prison (\"Hanoi Hilton\") — open daily, Hanoi's most gripping museum",
          "see| Train Street — café trackside for the ~15:15 train; Long Bien Bridge a free fallback",
          "? Hang Gai Street — silk, lacquerware, art galleries (if there's time)",
        ]},
        { h: "Sunset — West Lake (Grab out, ~20 min)", items: [
          "Tran Quoc Pagoda — Hanoi's oldest, on the lake causeway (on the way in)",
          "🌟 Nagocha Matcha — the West Lake flagship tea house",
          "Phu Tay Ho temple + banh tom (shrimp cakes) on the food street",
          "Sunset cafe on the east shore — Maison de Tet Decor or C'est Bon",
        ]},
      ],
      stay: "La Passion Premium Cau Go",
      foot: ["Early risers fit it all — otherwise Hoa Lo ↔ Temple of Literature are an easy either/or, both quick", "🌧️ Wet day? Hoa Lo + Raw Compound + Matcha Space are all indoor"] },

    { n: 3, title: "Ha Long Bay — Mon Cheri Cruise", date: "Tue 23 Jun", iso: "2026-06-23", city: "halong",
      tags: [["Adventure","blush"],["Cruise","sage"]],
      cols: [
        { h: "Morning — transfer", items: [
          "Hotel pickup ~08:00–08:50 from the Old Quarter — ~3 hr transfer to Tuan Chau Marina, Ha Long",
          "Marina check-in 11:30 → board ~12:00 by tender (Mon Cheri, conf: 6223585718)",
        ]},
        { h: "Afternoon — into Lan Ha Bay", items: [
          "13:00 welcome drinks + lunch as you cruise out to Lan Ha Bay",
          "✅ Kayaking at Tra Bau (~15:30) — or the onboard Jacuzzi pool",
          "Swimming in the bay (weather permitting)",
        ]},
        { h: "Evening — onboard", items: [
          "Cooking demo — Vietnamese spring rolls (~17:30) + sunset on the top deck",
          "Happy hour (buy-one-get-one), dinner ~19:30, then squid fishing off the deck",
        ]},
      ],
      stay: "Mon Cheri Cruises",
      foot: [
        "🌧️ Rain just reroutes the boat — only a storm cancels, and the harbour authority calls it by ~3pm (100% refund; travel insurance is included).",
        "Backup if cancelled: a Ninh Binh / Trang An day trip ('Ha Long on land' — sampan through karst caves, rain-robust) beats a plain Hanoi day; otherwise an easy extra Hanoi day (Hoa Lo, West Lake, puppets). Day-4 flight is unaffected either way.",
        "Bring cash (drinks & tips aren't included, no ATMs on the bay), plus swimwear & sunscreen.",
      ] },

    { n: 4, title: "Ha Long → Hoi An (Travel Day)", date: "Wed 24 Jun", iso: "2026-06-24", city: "hoian",
      tags: [["Travel","pink"]],
      cols: [
        { h: "Morning — last of the cruise", items: [
          "Tai Chi at sunrise on deck (~06:00)",
          "Trung Trang Cave, Cat Ba Island — stalactite cavern (~07:30)",
          "Brunch + checkout, disembark Tuan Chau ~11:00",
          "Transfer Ha Long → Noi Bai Airport (~2.5–3 hrs) — straight to the airport, not the Old Quarter",
        ]},
        { h: "Afternoon & Evening — to Hoi An", items: [
          "VN 187 · HAN 17:25 → DAD 18:50 (Vietnam Airlines, booked)",
          "Grab Da Nang → Hoi An (~45 min)",
          "✅ Check in — Hotel Royal Hoi An (conf: 5760294192)",
          "⭐ Tailor measurements tonight — silk pajamas + clothes (shops open ~till 21:30). Burn-test the silk; get '100% mulberry silk' on the receipt",
          "First wander through Ancient Town at night — lanterns ✨",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang", foot: [] },

    { n: 5, title: "Hoi An — Temples, Tailoring & Food", date: "Thu 25 Jun", iso: "2026-06-25", city: "hoian",
      tags: [["Culture","blush"],["Shopping","lemon"],["Food","sage"]],
      cols: [
        { h: "Morning & Afternoon", items: [
          "✅ Banh Mi Phuong — best banh mi in Vietnam, grab breakfast first",
          "⭐ Tailor fitting this morning — try-on & adjustments (Izi / I Love Fashion), so they can finish it while you're out at My Son & the beach tomorrow",
          "🌟 Phuc Kien Assembly Hall — incense spirals",
          "Japanese Covered Bridge",
          "Shop for ready-made leather tabis — browse the leather shops (also keep an eye out in the HCMC streetwear stores)",
          "✅ Cam Thanh Coconut Village — basket boat ride 🛶",
          "✅ Quan Cao Iau Ba Le — white rose dumplings",
        ]},
        { h: "Evening", items: [
          "Hoi An Night Market — lanterns, street food, souvenirs",
          "✅ Morning Glory Restaurant — Cao Lau noodles",
          "🌟 Floating lantern boat on the Thu Bon — release a lantern (you miss the full-moon festival by a day, so do it tonight)",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang", foot: [] },

    { n: 6, title: "My Son & An Bang Beach", date: "Fri 26 Jun", iso: "2026-06-26", city: "hoian",
      tags: [["Culture","lilac"],["Beach","sage"],["Food","blush"]],
      cols: [
        { h: "Morning — My Son", items: [
          "✅ My Son Sanctuary — head out early to beat the heat & crowds (~1 hr drive). The Champa kingdom's royal temple-capital, 4th–14th c. brick towers",
          "Cham dance performance at the site (morning shows)",
          "? Tailoring fitting back in town on the way through, if anything needs a tweak",
        ]},
        { h: "Afternoon — An Bang Beach", items: [
          "do| 🌟 An Bang Beach — swim, loungers, seafood lunch on the sand (~15 min from town)",
          "? Sunset drinks at a beach bar — Soul Kitchen or La Plage",
        ]},
        { h: "Evening — Hoi An", items: [
          "Relaxed Old Town evening — lanterns + riverside dinner",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang",
      foot: [
        "🌧️ My Son is open-air — if it rains, swap in the Cham Museum (Da Nang) or a Hoi An cooking / lantern-making class.",
        "Your imperial-history fix without the 7-hr Hue haul: My Son (Champa) here + the Cham Museum on Day 8 (Temple of Literature in Hanoi covers the Vietnamese dynastic side).",
      ] },

    { n: 7, title: "Hoi An → Da Nang + Dragon Bridge", date: "Sat 27 Jun", iso: "2026-06-27", city: "danang",
      tags: [["Shopping","lemon"],["Travel","blush"],["Nightlife","lilac"]],
      cols: [
        { h: "Morning — Collect Tailoring", items: [
          "✅ Collect tailored clothing first thing — final try-on, allow time for one tweak before the ~12:00 departure",
          "Old Town last souvenir sweep",
          "Grab to Da Nang (~30 min)",
          "Check in — Chicland Boutique Danang Beach (conf: 6288175813)",
        ]},
        { h: "Afternoon & Evening 🐉", items: [
          "Ba Na Hills + Golden Bridge — book online (~500k VND pp)",
          "My Khe beachfront seafood",
          "🐉 Dragon Bridge fire & water show — 21:00 (SATURDAY!)",
        ]},
      ],
      stay: "Chicland Boutique Danang Beach Hotel", foot: [] },

    { n: 8, title: "Da Nang — Beaches & Bridges", date: "Sun 28 Jun", iso: "2026-06-28", city: "danang",
      tags: [["Beach","sage"],["Food","blush"]],
      cols: [
        { h: "Morning & Afternoon", items: [
          "My Khe Beach — sunrise swim 🏖️",
          "Son Tra Peninsula — Lady Buddha statue, monkey sightings",
          "✅ Marble Mountains — Buddhist cave temples, before 10am to beat heat",
          "Lunch at a beachfront seafood spot",
          "Museum of Cham Sculpture — the carvings pulled from My Son's towers; cool indoor midday stop, open daily",
        ]},
        { h: "Shopping — Vintage & Thrift", items: [
          "✅ An Thuong Street — full vintage strip, browse the whole street",
          "✅ Mango Archive — vintage clothing, your bold pick",
          "Rust Rack, Hana 34, ORI jewellery — all nearby",
        ]},
        { h: "Evening", items: [
          "🐉 Dragon Bridge fire & water show — 21:00 (SUNDAY!)",
          "Night market near the bridge",
          "Rooftop cocktails at Chicland",
        ]},
      ],
      stay: "Chicland Boutique Danang Beach Hotel", foot: [] },

    { n: 9, title: "Da Nang → Ho Chi Minh City", date: "Mon 29 Jun", iso: "2026-06-29", city: "hcmc",
      tags: [["Travel","pink"],["History","lilac"]],
      cols: [
        { h: "Morning", items: [
          "Last swim at My Khe before checkout",
          "Fly to Ho Chi Minh City — land early afternoon",
        ]},
        { h: "Afternoon & Evening", items: [
          "✅ Check in — ANIMA Boutique Hotel (conf: 6083452364)",
          "✅ War Remnants Museum — closes 17:00, go straight away",
          "Bui Vien Walking Street — food, drinks, energy",
        ]},
      ],
      stay: "ANIMA Boutique Hotel", foot: [] },

    { n: 10, title: "HCMC — Cu Chi Tunnels & Streetwear", date: "Tue 30 Jun", iso: "2026-06-30", city: "hcmc",
      tags: [["History","lilac"],["Shopping","lemon"]],
      cols: [
        { h: "Morning — Cu Chi Tunnels", items: [
          "✅ Cu Chi Tunnels half-day tour — depart 07:30, back by 13:00, book through hotel",
          "Crawl through the tunnel network — claustrophobia warning",
          "Shooting range (optional, ~60k VND for 10 rounds)",
        ]},
        { h: "Afternoon & Evening", items: [
          "Streetwear walk — The New Playground, 11 Garmentory, Compound Garment",
          "111 Concept Store — clothing, art, souvenirs",
          "L'Usine or Mockingbird Cafe — coffee between shopping",
          "? Golden Dragon Water Puppets — 50-min show by City Hall (~17:00/18:30), if you skipped it in Hanoi. Book ahead.",
          "Rooftop cocktails — EON Heli Bar or Chill Sky Bar",
        ]},
      ],
      stay: "ANIMA Boutique Hotel",
      foot: ["🌧️ Cu Chi is morning-only, streetwear is all indoor — fully rain-proof day"] },

    { n: 11, title: "HCMC — Food Crawl & Final Beer 🍺", date: "Wed 1 Jul", iso: "2026-07-01", city: "hcmc",
      tags: [["Food","blush"],["Shopping","lemon"]],
      cols: [
        { h: "Morning", items: [
          "🌟 Bo Ne Ba Nui — $4 Vietnamese steak breakfast, go first thing",
          "Notre-Dame Cathedral + Central Post Office — exterior only, under renovation until 2027, no indoor access",
          "Dong Khoi Street + Nguyen Hue Boulevard — main promenade, cafés, browsing",
        ]},
        { h: "Afternoon & Evening", items: [
          "Last shopping — Lotte Mart for Vietnamese coffee, cashews, souvenirs",
          "Ben Thanh Market — final souvenir sweep",
          "🍺 ★ Pasteur Street Brewing Company — final beer, HCMC's best craft brewery",
          "Pack for early departure",
        ]},
      ],
      stay: "ANIMA Boutique Hotel", foot: [] },

    { n: 12, title: "Departure", date: "Thu 2 Jul", iso: "2026-07-02", city: "hcmc",
      tags: [["Travel","pink"]],
      cols: [
        { h: "Last Morning", items: [
          "Check out of ANIMA",
          "One last Vietnamese coffee",
        ]},
        { h: "Afternoon", items: [
          "Head to Tan Son Nhat Airport",
          "SGN 20:00 → DOH → JNB 09:35+1 (3 Jul)",
        ]},
      ],
      stay: null,
      foot: ["✈️ Qatar Airways QR 3 · SGN 20:00 → JNB 09:35+1"] },
  ],

  // ── PLACES (feeds Places grid + map) ──
  // group: shown grouping in Places tab. wishlist:false => map-only.
  // cat: map filter category (coffee|food|shopping|sights|nightlife)
  places: [
    // Cafes & Matcha
    { name: "Cafe Giang", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The original egg coffee since 1946. Must-visit.",
      lat: 21.0334, lng: 105.8550, approx: false },
    { name: "Cafe Đinh", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The other 'original' egg coffee — hidden up a stairwell above a shop at 13 Đinh Tiên Hoàng, with a balcony over Hoan Kiem Lake. More local than Giang.",
      lat: 21.0298, lng: 105.8527, approx: false },
    { name: "The Note Coffee", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Four floors plastered wall-to-wall with handwritten sticky notes since 2012. Egg coffee and coconut frappe. 64 Lương Văn Can, just west of the lake.",
      lat: 21.0322, lng: 105.8505, approx: false },
    { name: "Nagocha Matcha", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Japanese matcha specialty & tea house — ceremonial grades and matcha flights. Flagship two-storey house at 38 Quảng An, West Lake; central branch at B1, 175 Nguyễn Thái Học.",
      lat: 21.0700, lng: 105.8235, approx: true },
    { name: "Artisan Matcha", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Long Biên", desc: "Matcha \"slow bar\" — creative matcha cocktails made tableside, part performance art. Across the river at Ngõ 5 Nguyễn Văn Cừ, Long Biên.",
      lat: 21.0445, lng: 105.8665, approx: true },
    { name: "(á) The Matcha Space", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Đống Đa", desc: "Minimalist matcha specialty cafe — single-origin matcha, lattes and desserts. 93B Ngõ 91 Trần Quang Diệu, Đống Đa. Open daily 9:00–22:00.",
      lat: 21.0185, lng: 105.8235, approx: true },
    { name: "Maison de Tết Décor", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Rustic farm-to-table cafe on West Lake — the classic Tây Hồ sunset spot. 26 Quảng Bá. Arrive by ~16:30 for a lakeside table.",
      lat: 21.0760, lng: 105.8205, approx: true },
    { name: "Magicha Zenbar", group: "☕ Cafes & Matcha", cat: "coffee", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Matcha spot — a calm last coffee in Hoi An.",
      lat: 15.8801, lng: 108.3300, approx: true },
    { name: "Reaching Out Teahouse", group: "☕ Cafes & Matcha", cat: "coffee", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Peaceful teahouse in a traditional heritage house in Hoi An Ancient Town, staffed entirely by speech- and hearing-impaired individuals. Premium Vietnamese teas and handmade cookies in a serene garden setting.",
      lat: 15.8800, lng: 108.3280, approx: true },
    { name: "43 Factory Coffee Roaster", group: "☕ Cafes & Matcha", cat: "coffee", city: "danang",
      catLabel: "Da Nang — Ngũ Hành Sơn", desc: "Sprudge-featured specialty roastery with a transparent roasting area and elegant design. One of Vietnam's most serious coffee destinations — in-house roasting, pour-overs, and espresso.",
      lat: 16.0470, lng: 108.2470, approx: true },

    // Food & Drink
    { name: "Ta Hien & Nguyen Trung Truc Streets", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Bun cha, banh cuon, grilled corn — eat everything you see on these food streets.",
      lat: 21.0345, lng: 105.8525, approx: false },
    { name: "Bia Hoi Corner", group: "🍜 Food & Drink", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "25c draught beer on plastic stools. Local institution at Luong Ngoc Quyen.",
      lat: 21.0344, lng: 105.8516, approx: false },
    { name: "Bún chả Hương Liên", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Hai Bà Trưng", desc: "The 'Obama bun cha' — where Obama & Anthony Bourdain ate in 2016 (the combo is on the menu). Smoky grilled pork & noodles. 24 Lê Văn Hưu.",
      lat: 21.0188, lng: 105.8517, approx: false },
    { name: "Quan Cao Iau Ba Le", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "White rose dumplings — can only be made authentically in Hoi An's water.",
      lat: 15.8806, lng: 108.3275, approx: true },
    { name: "Morning Glory Restaurant", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Cao Lau noodles — the signature Hoi An noodle, only properly made here.",
      lat: 15.8769, lng: 108.3270, approx: false },

    // Shopping
    { name: "Old Quarter Night Market", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Friday to Sunday nights, 6–11pm (busiest 7–10pm). Hang Dao up to Dong Xuan Market — shoes, clothes, streetwear, souvenirs, food stalls.",
      lat: 21.0355, lng: 105.8497, approx: false },
    { name: "Hoi An Night Market", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Every night. Lanterns, street food, souvenirs, best atmosphere in town.",
      lat: 15.8760, lng: 108.3290, approx: false },
    { name: "Izi Tailor & I Love Fashion", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Get measured on day 1, collect on day 3. Custom suits, dresses, leather goods.",
      lat: 15.8790, lng: 108.3285, approx: true },
    { name: "Ben Thanh Market", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Knock-offs, souvenirs, produce, local snacks. The classic HCMC market.",
      lat: 10.7723, lng: 106.6980, approx: false },
    { name: "The New Playground", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Underground streetwear hub at 26 Lý Tự Trọng — 20+ local brands under one roof. Open 10:00–21:30.",
      lat: 10.7770, lng: 106.6968, approx: false },
    { name: "Rue Miche", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Multi-brand fashion boutique in a restored 1952 French colonial villa. 25+ curated local brands. 9B Phùng Khắc Khoan.",
      lat: 10.7869, lng: 106.6928, approx: true },
    { name: "Das Studios", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Leading Vietnamese menswear brand — clean contemporary cuts with a sharp eye on tailoring.",
      lat: 10.7800, lng: 106.6990, approx: true },
    { name: "Lider", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Trendy unisex fashion at 7 Tôn Thất Thiệp. Clean cuts, flare jeans, streetwear. Also at The New Playground B2.",
      lat: 10.7732, lng: 106.7035, approx: true },
    { name: "AASTU (AA Flagship Store)", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "American-style Vietnamese menswear at 118/12 Trần Quang Diệu. Clean lines, contemporary cuts, friendly staff.",
      lat: 10.7880, lng: 106.6860, approx: true },
    { name: "Wardrobe Arc", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Retail complex with 20+ local streetwear brands at 351/44 Lê Văn Sỹ. Dark palettes, bold young streetwear. Open 9:30–21:30.",
      lat: 10.7920, lng: 106.6760, approx: true },
    { name: "Aesir Studios", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Thảo Điền", desc: "German-Vietnamese designer streetwear. AE Space at 20 Duong 46, Thao Dien + flagship at 128G Nguyễn Đình Chính.",
      lat: 10.8030, lng: 106.7340, approx: true },
    { name: "Lumla Glasses", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Vietnam's most viral sunglasses store — huge selection of trendy frames at great prices. 51 Lê Thị Riêng, D1.",
      lat: 10.7720, lng: 106.6910, approx: true },
    { name: "Seeson", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Contemporary Vietnamese eyewear — handcrafted acetate frames with an optometry clinic and cafe in-store. Flagship on Nam Kỳ Khởi Nghĩa, D1.",
      lat: 10.7850, lng: 106.6950, approx: true },
    { name: "Rue Miche L'Édition", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Rue Miche's new flagship retail hub (Aug 2025) — 30+ local designers, plus Rotten Bar and a wellness space. LL3 (B3), Union Square, 171 Đồng Khởi. Open 10:00–21:00.",
      lat: 10.7770, lng: 106.7035, approx: true },
    { name: "Đầu Hàng", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Đa Kao", desc: "\"Home of curated goods\" — vintage garments, statement jewellery and funky housewares. Main store 26/78 Nguyễn Bỉnh Khiêm, Đa Kao. Open 10:00–20:30.",
      lat: 10.7882, lng: 106.7005, approx: true },
    { name: "Untilfaded", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Tân Định", desc: "Vintage & designer finds, sun-dried for months to that perfect faded look. 82/2 Võ Thị Sáu, Tân Định.",
      lat: 10.7905, lng: 106.6895, approx: true },
    { name: "Metiseko", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Eco-conscious fashion and homeware brand at 140 Trần Phú. Organic cotton and mulberry silk clothing, accessories, and homewares — all made sustainably in Vietnam. A world away from the mass-market silk stalls.",
      lat: 15.8800, lng: 108.3280, approx: true },
    { name: "Zó Project", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Social enterprise preserving 800-year-old Vietnamese Dó paper. Handcrafted notebooks, postcards, and art supplies in a small shop near West Lake. Featured in the New York Times and BBC.",
      lat: 21.0470, lng: 105.8380, approx: true },

    // Things to Do
    { name: "Tran Quoc Pagoda", group: "🎯 Things to Do", cat: "sights", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Hanoi's oldest pagoda (6th century) on a tiny islet in West Lake — best at sunset. Easy add-on if you're heading to Nagocha at Tây Hồ.",
      lat: 21.0490, lng: 105.8377, approx: false },
    { name: "Phu Tay Ho", group: "🎯 Things to Do", cat: "sights", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Lakeside temple on the Quảng An peninsula, ~400 m from Nagocha — with a food street famous for bánh tôm (shrimp cakes) and bún ốc.",
      lat: 21.0722, lng: 105.8232, approx: true },
    { name: "My Son Sanctuary", group: "🎯 Things to Do", cat: "sights", city: "hoian",
      catLabel: "Hoi An — My Son (~40 km W)", desc: "The Champa kingdom's royal temple-capital — clusters of 4th–14th c. Hindu brick towers in a jungle valley. Go early (heat + crowds). UNESCO.",
      lat: 15.7640, lng: 108.1240, approx: false },
    { name: "An Bang Beach", group: "🎯 Things to Do", cat: "sights", city: "hoian",
      catLabel: "Hoi An — An Bang", desc: "Hoi An's best beach (~15 min from town) — loungers, beach bars (Soul Kitchen, La Plage), fresh seafood. A cooling afternoon escape.",
      lat: 15.9050, lng: 108.3450, approx: false },
    { name: "Museum of Cham Sculpture", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Hai Chau", desc: "World's best Champa collection — the sandstone sculptures pulled from My Son's towers. Open daily, AC, a great midday heat-break. 2 Tháng 9 St.",
      lat: 16.0606, lng: 108.2233, approx: false },
    { name: "Ba Na Hills + Golden Bridge", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Ba Na Hills", desc: "World's longest cable car, giant stone hands, French Village. Book online (~500k VND pp).",
      lat: 15.9950, lng: 107.9960, approx: false },
    { name: "My Khe Beach", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — My Khe", desc: "Steps from Chicland. Sunrise swim, seafood on the sand.",
      lat: 16.0544, lng: 108.2470, approx: false },
    { name: "Dragon Bridge 🐉", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Riverfront", desc: "Fire & water show Friday, Saturday & Sunday at 21:00. You're there for both weekend nights!",
      lat: 16.0614, lng: 108.2275, approx: false },
    { name: "An Thuong Street + Mango Archive", group: "🎯 Things to Do", cat: "shopping", city: "danang",
      catLabel: "Da Nang — An Thuong", desc: "Full vintage strip with Mango Archive (your pick), Rust Rack, Hana 34, ORI jewellery. Afternoon stroll near the beachfront.",
      lat: 16.0440, lng: 108.2440, approx: true },
    { name: "War Remnants Museum", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Essential and powerful. Go straight from hotel — closes 17:00.",
      lat: 10.7795, lng: 106.6917, approx: false },
    { name: "Golden Dragon Water Puppets", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "HCMC's main water-puppet theatre — 50-min show, ~17:00 / 18:30 / 19:45. 55B Nguyễn Thị Minh Khai, by City Hall. Book ahead. The Saigon stand-in if you skip the Hanoi puppets.",
      lat: 10.7785, lng: 106.6955, approx: true },
    { name: "Chu Chi Tunnels", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — Day Trip", desc: "Half-day tour. Crawl the tunnel network, shooting range optional (~60k VND).",
      lat: 11.1417, lng: 106.4640, approx: false },
    { name: "Bui Vien Walking Street", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Food, drinks, backpacker energy. Nightlife central.",
      lat: 10.7670, lng: 106.6920, approx: false },
    { name: "Saigon River Rooftop Bars", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — Riverfront", desc: "Skyline views over the river. Perfect for the last night.",
      lat: 10.7720, lng: 106.7050, approx: true },
    { name: "Workshop14", group: "🎯 Things to Do", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Hidden speakeasy cocktail bar in Tây Hồ district, set in a former architect's studio on the site of a 12th-century royal palace. Asia's 50 Best Bars 2025 (#83). Stripped-back concrete design with skylights, natural materials, and serene lighting.",
      lat: 21.0500, lng: 105.8300, approx: true },
    { name: "STIR — Modern Classic Cocktail", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "First-floor speakeasy in a colonial-era alleyway near Ben Thanh Market. Asia's 50 Best Bars mainstay (#61 in 2025). Vietnamese-ingredient cocktails like 'Xôi Mít' (jackfruit, jasmine, sticky rice, peated Scotch) alongside faithful classics.",
      lat: 10.7730, lng: 106.6970, approx: true },

    // ── map-only landmarks (wishlist:false) ──
    { name: "Hoan Kiem Lake & Ngoc Son Temple", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The heart of the Old Quarter — lake, red bridge, island temple. Temple 8:00–18:00.",
      lat: 21.0287, lng: 105.8524, approx: false },
    { name: "Hoa Lo Prison", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Hoan Kiem", desc: "The \"Hanoi Hilton\" — gripping, well-curated museum. Open daily 8:00–17:00.",
      lat: 21.0254, lng: 105.8466, approx: false },
    { name: "Temple of Literature", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi", desc: "Vietnam's oldest university (1070).",
      lat: 21.0273, lng: 105.8355, approx: false },
    { name: "Ho Chi Minh Mausoleum & Museum", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Ba Dinh", desc: "Mausoleum, museum, One Pillar Pagoda. Mausoleum closed Mondays.",
      lat: 21.0368, lng: 105.8350, approx: false },
    { name: "Train Street", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi", desc: "Trains pass inches from the cafes. Check current access rules.",
      lat: 21.0245, lng: 105.8412, approx: false },
    { name: "Thang Long Water Puppet Theatre", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Traditional water puppetry, ~1 hr. Book ahead.",
      lat: 21.0294, lng: 105.8538, approx: false },
    { name: "Sung Sot Cave", group: "_map", wishlist: false, cat: "sights", city: "halong",
      catLabel: "Ha Long Bay", desc: "Cathedral-sized cave chambers — the cruise's headline stop.",
      lat: 20.8425, lng: 107.1056, approx: true },
    { name: "Banh Mi Phuong", group: "_map", wishlist: false, cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Famous banh mi — Anthony Bourdain's pick. Breakfast go-to.",
      lat: 15.8783, lng: 108.3300, approx: false },
    { name: "Phuc Kien Assembly Hall", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Ornate Fujian temple with hanging incense spirals.",
      lat: 15.8773, lng: 108.3283, approx: false },
    { name: "Japanese Covered Bridge", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "The 18th-century icon of Hoi An.",
      lat: 15.8770, lng: 108.3258, approx: false },
    { name: "Cam Thanh Coconut Village", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An", desc: "Basket boat rides through the water-coconut palms.",
      lat: 15.8920, lng: 108.3640, approx: true },
    { name: "Marble Mountains", group: "_map", wishlist: false, cat: "sights", city: "danang",
      catLabel: "Da Nang", desc: "Five limestone hills with Buddhist cave temples. Go before 10am.",
      lat: 16.0036, lng: 108.2630, approx: false },
    { name: "Lady Buddha (Linh Ung Pagoda)", group: "_map", wishlist: false, cat: "sights", city: "danang",
      catLabel: "Da Nang — Son Tra", desc: "67m white statue on the Son Tra Peninsula. Monkeys about.",
      lat: 16.1003, lng: 108.2780, approx: false },
    { name: "Notre-Dame Cathedral & Post Office", group: "_map", wishlist: false, cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Exterior only — under renovation until 2027.",
      lat: 10.7797, lng: 106.6990, approx: false },
    { name: "Nguyen Hue Boulevard", group: "_map", wishlist: false, cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Pedestrian promenade, cafes, the walking street's heart.",
      lat: 10.7740, lng: 106.7040, approx: false },
    { name: "Pasteur Street Brewing Co.", group: "_map", wishlist: false, cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "HCMC's best craft brewery — the final beer. 144 Pasteur.",
      lat: 10.7780, lng: 106.7030, approx: true },
  ],

  // ── PACKING ──
  packing: [
    { label: "Passports (valid 6+ months)" },
    { label: "E-visa approved", checked: true },
    { label: "Travel insurance purchased" },
    { label: "Flights booked — Qatar QR 8MXDM6", checked: true },
    { label: "Accommodation — all 5 stays booked", checked: true },
    { label: "Mon Cheri Cruises booked", checked: true },
    { label: "Copies of docs (digital + printed)" },
    { label: "Notify bank of travel" },
    { label: "Cash (VND) + card with no FX fees" },
    { label: "Light clothing — tropical weight" },
    { label: "Rain jacket / umbrella" },
    { label: "Swimwear" },
    { label: "Good walking shoes" },
    { label: "Insect repellent" },
    { label: "Sunscreen" },
    { label: "Power adapter (2-pin round)" },
    { label: "Portable charger" },
    { label: "Reusable water bottle" },
    { label: "Basic medicine kit" },
    { label: "Earplugs + eye mask" },
    { label: "Daypack for excursions" },
  ],

  // ── CURRENCY (live rate fetched at runtime; this is the offline fallback) ──
  currency: {
    base: "ZAR", quote: "VND",
    fallbackRate: 1450,            // ~1 ZAR in VND (approx, offline fallback)
    // quick amounts shown on the cheat-sheet (in VND)
    cheats: [20000, 50000, 100000, 200000, 500000, 1000000],
  },

  // ── VIETNAMESE PHRASES (offline) ──
  phrases: [
    { g: "Essentials", items: [
      ["Hello", "Xin chào", "sin chow"],
      ["Thank you", "Cảm ơn", "gam un"],
      ["Yes / No", "Vâng / Không", "vung / khom"],
      ["Sorry / Excuse me", "Xin lỗi", "sin loy"],
      ["I don't understand", "Tôi không hiểu", "toy khom hyoo"],
      ["Do you speak English?", "Bạn nói tiếng Anh không?", "ban noy tyeng anh khom"],
    ]},
    { g: "Eating & drinking", items: [
      ["The bill, please", "Tính tiền", "ting tyen"],
      ["Delicious!", "Ngon quá", "ngon kwa"],
      ["No ice", "Không đá", "khom da"],
      ["Not spicy", "Không cay", "khom kai"],
      ["Vegetarian", "Ăn chay", "an chai"],
      ["Cheers!", "Một, hai, ba, dô!", "mot hai ba yo"],
    ]},
    { g: "Shopping & getting around", items: [
      ["How much?", "Bao nhiêu tiền?", "bow nyew tyen"],
      ["Too expensive", "Đắt quá", "dat kwa"],
      ["Where is…?", "…ở đâu?", "uh dow"],
      ["Stop here", "Dừng ở đây", "zung uh day"],
      ["Toilet", "Nhà vệ sinh", "nya ve sing"],
    ]},
    { g: "Numbers", items: [
      ["1 / 2 / 3", "một / hai / ba", "mot / hai / ba"],
      ["4 / 5 / 6", "bốn / năm / sáu", "bon / nam / sow"],
      ["7 / 8 / 9", "bảy / tám / chín", "bai / tam / chin"],
      ["10 / 100 / 1000", "mười / trăm / nghìn", "muoi / cham / ngin"],
    ]},
    { g: "Emergency words", items: [
      ["Help!", "Cứu tôi!", "gew toy"],
      ["Hospital", "Bệnh viện", "ben vyen"],
      ["Doctor", "Bác sĩ", "bak see"],
      ["Police", "Công an", "kom an"],
    ]},
  ],

  // ── EMERGENCY (offline) ──
  emergency: {
    numbers: [
      { label: "Police", num: "113", icon: "🚓" },
      { label: "Ambulance", num: "115", icon: "🚑" },
      { label: "Fire", num: "114", icon: "🚒" },
    ],
    notes: [
      { label: "SA Embassy, Hanoi", detail: "31 Hai Bà Trưng, Hoàn Kiếm, Hanoi", tel: "+842439362000", verify: true },
      { label: "SA Consulate, HCMC", detail: "Saigon Tower, 29 Lê Duẩn, District 1", tel: "+842838235945", verify: true },
    ],
    tip: "Save these offline. For a taxi, show the driver your hotel from the Stays list — tap any stay for its pin and Vietnamese area name.",
  },
};
