/* ─────────────────────────────────────────────────────────────
   VIETNAM TRIP — single source of truth.
   Everything (day cards, places grid, map pins, stays) renders
   from this object. Add a place once and it appears everywhere.

   Coordinates: landmarks are accurate; small shops/cafes are
   approximate (approx:true) — nudge them if a pin is off.
   ───────────────────────────────────────────────────────────── */
const TRIP = {
  meta: {
    title: "Vietnam",
    travelers: "Don & Katelyn",
    start: "2026-06-21",
    end:   "2026-07-02",
    updated: "Jun 17, 2026",
  },

  // city id -> palette colour
  cities: [
    { id: "hanoi",  name: "Hanoi",       emoji: "🇻🇳", color: "pink",  nights: "2 nights", lat: 21.0285, lng: 105.8542 },
    { id: "halong", name: "Ha Long Bay", emoji: "🚢", color: "blush", nights: "1 night",  lat: 20.9101, lng: 107.1839 },
    { id: "hoian",  name: "Hoi An",      emoji: "🏮", color: "sage",  nights: "3 nights", lat: 15.8801, lng: 108.3380 },
    { id: "danang", name: "Da Nang",     emoji: "🏖️", color: "lemon", nights: "2 nights", lat: 16.0544, lng: 108.2022 },
    { id: "hcmc",   name: "HCMC",        emoji: "🏙️", color: "lilac", nights: "3 nights", lat: 10.7769, lng: 106.7009 },
  ],

  stats: [
    { num: "11",    label: "Days",   color: "pink"  },
    { num: "5",     label: "Cities", color: "lemon" },
    { num: "5",     label: "Stays",  color: "sage"  },
    { num: "1,700", label: "km",     color: "lilac" },
  ],

  flights: {
    ref: "8MXDM6", airline: "Qatar Airways",
    outbound: { label: "Outbound", airline: "20 Jun · JNB 12:40 → DOH", route: "Doha → Hanoi", time: "Arrive HAN 13:25 (21 Jun)" },
    domestic: { label: "Domestic", airline: "24 Jun · HAN 17:25 → DAD 18:50", route: "Hanoi → Da Nang", time: "VN 187 · Vietnam Airlines · 1h25m" },
    domestic2: { label: "Domestic", airline: "29 Jun · DAD 13:50 → SGN 15:15", route: "Da Nang → Ho Chi Minh City", time: "VN 6037 · Vietnam Airlines · ~1h25m" },
    inbound:  { label: "Return",   airline: "2 Jul · SGN 20:00 → DOH",  route: "Doha → Johannesburg", time: "Arrive JNB 09:35 (3 Jul)" },
    note: "~R16,462 pp · Qatar booking ref 8MXDM6",
  },

  // ── STAYS ──
  stays: [
    { name: "La Passion Premium Cau Go", city: "hanoi",  loc: "Hanoi — Old Quarter",
      dates: "Sun 21 Jun – Tue 23 Jun · 2 nights", confirm: "5963820548", phone: "+84886087576",
      lat: 21.0322, lng: 105.8541, est: "R3,300", nights: "2", approx: false },
    { name: "Mon Cheri Cruises", city: "halong", loc: "Ha Long Bay",
      dates: "Tue 23 Jun – Wed 24 Jun · 1 night", confirm: "6223585718", phone: "+84946982299",
      lat: 20.9101, lng: 107.0700, est: "~R5,500", nights: "1 (cruise)", approx: true },
    { name: "Hotel Royal Hoi An, Danang", city: "hoian", loc: "Hoi An",
      dates: "Wed 24 Jun – Sat 27 Jun · 3 nights", confirm: "5760294192", phone: "+842353950777",
      lat: 15.8803, lng: 108.3256, est: "~R6,000", nights: "3", approx: true },
    { name: "Chicland Boutique Danang Beach Hotel", city: "danang", loc: "Da Nang — My Khe Beach",
      dates: "Sat 27 Jun – Mon 29 Jun · 2 nights", confirm: "6288175813", phone: "+842362232222",
      lat: 16.0556, lng: 108.2455, est: "~R3,600", nights: "2", approx: false },
    { name: "ANIMA Boutique Hotel", city: "hcmc", loc: "HCMC — District 1",
      dates: "Mon 29 Jun – Thu 2 Jul · 3 nights", confirm: "6083452364", phone: "+84833881010",
      lat: 10.7690, lng: 106.6940, est: "~R6,900", nights: "3", approx: true },
  ],
  budgetTotal: "~R25,300",
  budgetNote: "All 5 stays confirmed on Booking.com. Estimates based on typical rates.",

  // ── DAYS ──
  days: [
    { n: 1, title: "Arrival in Hanoi", date: "Sun 21 Jun", iso: "2026-06-21", city: "hanoi",
      tags: [["Half day","pink"],["Matcha","sage"],["Food","blush"]],
      cols: [
        { h: "Afternoon — arrival", items: [
          "Land HAN 13:25 → transfer to the Old Quarter, check in (La Passion Premium Cau Go, conf: 5963820548)",
          "? Artisan Matcha Slow Bar (Long Bien) — drop bags & head straight there, closes 17:00. Skip if the flight's late or you're wiped — you'll still get Nagocha tomorrow.",
          "Hoan Kiem Lake + Ngoc Son Temple (temple closes 18:00)",
          "⭐ Cafe Giang — the original egg coffee since 1946 (open late, so flexible)",
        ]},
        { h: "Evening — Old Quarter", items: [
          "⭐ Street food crawl — Ta Hien & Nguyen Trung Truc",
          "Bia Hoi Corner — 25c draught beer on plastic stools",
          "🌟 Old Quarter Night Market — open tonight (Fri–Sun), Hang Dao → Dong Xuan",
          "? Nightcap — Nê Cocktail Bar (the 'Phở Cocktail') or the jazz-and-leather Polite & Co, if you've energy left",
          "? Water puppets — Thang Long Theatre by the lake (the original venue; or save it for Saigon)",
        ]},
      ],
      stay: "La Passion Premium Cau Go",
      foot: ["🌧️ Rainy backup: Cafe Giang → Dong Xuan covered market", "Loose plan — grab what you fancy, drop the rest"] },

    { n: 2, title: "Hanoi — City Sweep & West Lake Sunset", date: "Mon 22 Jun", iso: "2026-06-22", city: "hanoi",
      tags: [["History","pink"],["Shopping","lemon"],["Matcha","sage"]],
      cols: [
        { h: "Morning — Dong Da / Ba Dinh (west)", items: [
          "⭐ Breakfast — Phở Gia Truyền (49 Bát Đàn), the definitive Hanoi beef phở; a short walk in the Old Quarter, go early before it sells out, then Grab west",
          "✅ Temple of Literature — Vietnam's oldest university (open Mon)",
          "? One Pillar Pagoda + Ba Dinh Square — grounds only (Mausoleum & HCM Museum closed Mon)",
          "⭐ The Raw Compound — 20+ local streetwear brands, 180 La Thanh",
          "The Matcha Space — quick matcha pop-in, right by Raw Compound",
        ]},
        { h: "Lunch", items: [
          "⭐ Bún chả Hương Liên — the Obama–Bourdain bun cha (a lunch dish; open till 20:00)",
        ]},
        { h: "Afternoon — central + Old Quarter", items: [
          "🌟 Hoa Lo Prison (\"Hanoi Hilton\") — open daily, Hanoi's most gripping museum",
          "see| Train Street — café trackside for the ~15:15 train; Long Bien Bridge a free fallback",
          "? Zaker Store — branded fashion outlet on Hàng Bông, export-label hunt (Nike, Adidas, TNF, Puma). Right in the Old Quarter shopping strip.",
          "? Hang Gai Street — silk, lacquerware, art galleries (if there's time)",
        ]},
        { h: "Sunset — West Lake (Grab out, ~20 min)", items: [
          "Tran Quoc Pagoda — Hanoi's oldest, on the lake causeway (on the way in)",
          "🌟 Nagocha Matcha — the West Lake flagship tea house",
          "Phu Tay Ho temple + banh tom (shrimp cakes) on the food street",
          "Sunset cafe on the east shore — Maison de Tet Decor or C'est Bon",
          "🌟 Workshop14 — sundowner cocktail right here in Tây Hồ (Asia's 50 Best Bars #83), a stunning concrete speakeasy; do it before you Grab back",
          "Dinner back in the Old Quarter — ⭐ Chả Cá Lã Vọng, the turmeric-&-dill grilled fish institution since 1871 (14 Chả Cá)",
        ]},
      ],
      stay: "La Passion Premium Cau Go",
      foot: ["Early risers fit it all — otherwise Hoa Lo ↔ Temple of Literature are an easy either/or, both quick", "🌧️ Wet day? Hoa Lo + Raw Compound + Matcha Space are all indoor"] },

    { n: 3, title: "Ha Long Bay — Mon Cheri Cruise", date: "Tue 23 Jun", iso: "2026-06-23", city: "halong",
      tags: [["Adventure","blush"],["Cruise","sage"]],
      cols: [
        { h: "Morning — transfer", items: [
          "Hotel pickup ~08:00–08:50 from the Old Quarter — ~3 hr transfer to Tuan Chau Marina, Ha Long",
          "Marina check-in 11:30 → board ~12:00 by tender (Mon Cheri, conf: 6223585718)",
        ]},
        { h: "Afternoon — into Lan Ha Bay", items: [
          "13:00 welcome drinks + lunch as you cruise out to Lan Ha Bay",
          "✅ Kayaking at Tra Bau (~15:30) — or the onboard Jacuzzi pool",
          "Swimming in the bay (weather permitting)",
        ]},
        { h: "Evening — onboard", items: [
          "Cooking demo — Vietnamese spring rolls (~17:30) + sunset on the top deck",
          "Happy hour (buy-one-get-one), dinner ~19:30, then squid fishing off the deck",
        ]},
      ],
      stay: "Mon Cheri Cruises",
      foot: [
        "🌧️ Rain just reroutes the boat — only a storm cancels, and the harbour authority calls it by ~3pm (100% refund; travel insurance is included).",
        "Backup if cancelled: a Ninh Binh / Trang An day trip ('Ha Long on land' — sampan through karst caves, rain-robust) beats a plain Hanoi day; otherwise an easy extra Hanoi day (Hoa Lo, West Lake, puppets). Day-4 flight is unaffected either way.",
        "Bring cash (drinks & tips aren't included, no ATMs on the bay), plus swimwear & sunscreen.",
      ] },

    { n: 4, title: "Ha Long → Hoi An (Travel Day)", date: "Wed 24 Jun", iso: "2026-06-24", city: "hoian",
      tags: [["Travel","pink"]],
      cols: [
        { h: "Morning — last of the cruise", items: [
          "Tai Chi at sunrise on deck (~06:00)",
          "Trung Trang Cave, Cat Ba Island — stalactite cavern (~07:30)",
          "Brunch + checkout, disembark Tuan Chau ~11:00",
          "Transfer Ha Long → Noi Bai Airport (~2.5–3 hrs) — straight to the airport, not the Old Quarter",
        ]},
        { h: "Afternoon & Evening — to Hoi An", items: [
          "VN 187 · HAN 17:25 → DAD 18:50 (Vietnam Airlines, booked)",
          "Grab Da Nang → Hoi An (~45 min)",
          "✅ Check in — Hotel Royal Hoi An (conf: 5760294192)",
          "⭐ Tailor measurements tonight — silk pajamas + clothes (shops open ~till 21:30). Burn-test the silk; get '100% mulberry silk' on the receipt",
          "First wander through Ancient Town at night — lanterns ✨",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang", foot: [] },

    { n: 5, title: "Hoi An — Temples, Tailoring & Food", date: "Thu 25 Jun", iso: "2026-06-25", city: "hoian",
      tags: [["Culture","blush"],["Shopping","lemon"],["Food","sage"]],
      cols: [
        { h: "Morning & Afternoon", items: [
          "✅ Banh Mi Phuong — best banh mi in Vietnam, grab breakfast first",
          "⭐ Tailor fitting this morning — try-on & adjustments (Izi / I Love Fashion), so they can finish it while you're out at My Son & the beach tomorrow",
          "🌟 Phuc Kien Assembly Hall — incense spirals",
          "Japanese Covered Bridge",
          "Shop for ready-made leather tabis — browse the leather shops (try Hoan Bespoke Leather; also keep an eye out in the HCMC streetwear stores)",
          "✅ Cam Thanh Coconut Village — basket boat ride 🛶",
          "✅ Quán Cao Lầu Bà Lê — white rose dumplings",
        ]},
        { h: "Evening", items: [
          "Hoi An Night Market — lanterns, street food, souvenirs",
          "✅ Morning Glory Restaurant — Cao Lau noodles",
          "? Foodie dinner — Mango Rooms (riverfront, book a terrace table) or tiny Nữ Eatery for modern small plates",
          "🌟 Floating lantern boat on the Thu Bon — release a lantern (you miss the full-moon festival by a day, so do it tonight)",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang", foot: [] },

    { n: 6, title: "My Son & An Bang Beach", date: "Fri 26 Jun", iso: "2026-06-26", city: "hoian",
      tags: [["Culture","lilac"],["Beach","sage"],["Food","blush"]],
      cols: [
        { h: "Morning — My Son", items: [
          "✅ My Son Sanctuary — head out early to beat the heat & crowds (~1 hr drive). The Champa kingdom's royal temple-capital, 4th–14th c. brick towers",
          "Cham dance performance at the site (morning shows)",
          "? Tailoring fitting back in town on the way through, if anything needs a tweak",
        ]},
        { h: "Afternoon — An Bang Beach", items: [
          "do| 🌟 An Bang Beach — swim, loungers, seafood lunch on the sand (~15 min from town)",
          "? Sunset drinks at a beach bar — Soul Kitchen or La Plage",
        ]},
        { h: "Evening — Hoi An", items: [
          "Relaxed Old Town evening — lanterns + riverside dinner",
        ]},
      ],
      stay: "Hotel Royal Hoi An, Danang",
      foot: [
        "🌧️ My Son is open-air — if it rains, swap in the Cham Museum (Da Nang) or a Hoi An cooking / lantern-making class.",
        "Your imperial-history fix without the 7-hr Hue haul: My Son (Champa) here + the Cham Museum on Day 8 (Temple of Literature in Hanoi covers the Vietnamese dynastic side).",
      ] },

    { n: 7, title: "Hoi An → Da Nang + Dragon Bridge", date: "Sat 27 Jun", iso: "2026-06-27", city: "danang",
      tags: [["Travel","blush"],["Beach","sage"],["Nightlife","lilac"]],
      cols: [
        { h: "Morning — Collect Tailoring", items: [
          "✅ Collect tailored clothing first thing — final try-on, allow time for one tweak before the ~12:00 departure",
          "Old Town last souvenir sweep",
          "Grab to Da Nang (~30 min)",
          "Check in — Chicland Boutique Danang Beach (conf: 6288175813)",
        ]},
        { h: "Afternoon & Evening 🐉", items: [
          "🏖️ Settle in, then My Khe Beach — afternoon swim & sunset right out front",
          "? Magicha Zenbar — matcha pop-in (Hải Châu, central; open till 22:00) for your Da Nang matcha fix",
          "? Son Tra Peninsula — Lady Buddha statue (67m) & monkey sightings; ~15 min drive up the headland for late-afternoon views",
          "My Khe beachfront seafood dinner — Bé Mặn (pick-your-own from the trays, packed with locals)",
          "? Sky36 — Vietnam's highest rooftop bar, perfectly placed for a drink over the Dragon Bridge (36 Bạch Đằng)",
          "🐉 Dragon Bridge fire & water show — 21:00 (SATURDAY!)",
        ]},
      ],
      stay: "Chicland Boutique Danang Beach Hotel",
      foot: [
        "Plenty of time for it all: beach early afternoon → Magicha matcha break → Son Tra for late-day views → seafood dinner → 21:00 bridge. Magicha's open till 22:00, so it's flexible (afternoon break or post-dinner). The only real either/or is sunset itself — beach out front vs the view from Son Tra.",
      ] },

    { n: 8, title: "Da Nang — Golden Bridge & Coast", date: "Sun 28 Jun", iso: "2026-06-28", city: "danang",
      tags: [["Sights","sage"],["Shopping","lemon"],["Nightlife","lilac"]],
      cols: [
        { h: "Morning — Ba Na Hills (early!)", items: [
          "⭐ Grab to Ba Na Hills (~45 min, inland west) — aim for the cable car at opening ~08:00 to beat the crowds & summit fog",
          "🌟 Golden Bridge — the giant stone hands — plus French Village & Fantasy Park",
          "Book tickets online ahead (~900k VND pp); full morning up top, ride down early afternoon",
          "Lunch up top — French Village restaurants or the buffet (you're on the mountain over midday)",
        ]},
        { h: "Afternoon — Back on the Coast", items: [
          "Grab back into Da Nang (~45 min)",
          "✅ An Thuong Street — full vintage strip; Mango Archive (your bold pick), Rust Rack, Hana 34, ORI jewellery",
          "? 43 Factory Coffee — Da Nang's serious specialty roaster (An Thượng beach quarter, near the vintage strip)",
          "? Museum of Cham Sculpture — cool indoor stop, the carvings from My Son; doubles as a fog/rain backup if Ba Na's a wash",
        ]},
        { h: "Evening", items: [
          "Mì Quảng 1A — Da Nang's signature turmeric noodles, casual & Michelin-listed (5 Hải Phòng)",
          "🐉 Dragon Bridge fire & water show — 21:00 (SUNDAY!)",
          "Son Tra Night Market — riverside stalls just east of the bridge",
          "Rooftop cocktails at Chicland",
        ]},
      ],
      stay: "Chicland Boutique Danang Beach Hotel",
      foot: [
        "Ba Na eats the morning + early afternoon, so Day 8 runs tighter — Son Tra / Lady Buddha and a Day-8 sunrise swim drop off (do your beach time Day 7 evening instead).",
        "If Ba Na fogs in or you'd rather skip it, this flips back to an easy coast day: My Khe + Cham Museum + An Thuong, no rush (Marble Mountains is locked in for Day 9 morning).",
      ] },

    { n: 9, title: "Da Nang → Ho Chi Minh City", date: "Mon 29 Jun", iso: "2026-06-29", city: "hcmc",
      tags: [["Travel","pink"],["History","lilac"]],
      cols: [
        { h: "Morning — Marble Mountains", items: [
          "⭐ Marble Mountains — go early (opens 07:30) to beat the heat: marble caves, pagodas & coastal viewpoints, ~10 min from the hotel (~1.5–2 hr)",
          "? Quick last swim at My Khe, then checkout",
          "Grab to the airport → VN 6037, DAD 13:50 → SGN 15:15 (~1h25)",
        ]},
        { h: "Afternoon & Evening — HCMC", items: [
          "✅ Land late afternoon → check in ANIMA Boutique Hotel (conf: 6083452364)",
          "🌟 Dinner — Noriboi Omakase — ✅ BOOKED 20:00, 2 guests (2 Taki sets). Your first Saigon night is omakase.",
          "Quán Bụi (backup) — polished traditional Vietnamese in a leafy colonial setting (17A Ngô Văn Năm); bumped by Noriboi, move to another HCMC night if you want it",
          "Bui Vien Walking Street — food, drinks, energy",
        ]},
      ],
      stay: "ANIMA Boutique Hotel",
      foot: [
        "Aim for a DAD→SGN flight departing ~13:00–14:00 — clears the early Marble Mountains visit + checkout, lands ~15:00, and still leaves a free first evening in Saigon.",
        "Landing late afternoon means War Remnants (closes 17:00) moves to Day 10 or 11 — no problem, HCMC has 3 nights of slack.",
      ] },

    { n: 10, title: "HCMC — Streetwear & Vintage 🛍️", date: "Tue 30 Jun", iso: "2026-06-30", city: "hcmc",
      tags: [["Shopping","lemon"],["Food","blush"],["Nightlife","lilac"]],
      cols: [
        { h: "Late Morning — Streetwear & Designer (D1 core)", items: [
          "shop| ⭐ The New Playground — 20+ brands under one roof (26 Lý Tự Trọng); Lider in the basement",
          "shop| ⭐ Rue Miche L'Édition — 30+ designers at Union Square (171 Đồng Khởi)",
          "shop| 🌟 Compound Garment, Waa Studio (bags) & The Idiot — the Nguyễn Thái Bình cluster, all walkable by Ben Thanh",
          "shop| Seeson & Lumla — Vietnamese eyewear, District 1",
        ]},
        { h: "Lunch — in the cluster", items: [
          "🌟 Phở Việt Nam — Michelin hot-stone-bowl pho (14 Phạm Hồng Thái), right by the shops",
          "? Boulevard Gelato — gelato & coffee pit-stop (25 Hồ Tùng Mậu)",
        ]},
        { h: "Afternoon — Tân Định Vintage & Archive (walkable loop)", items: [
          "shop| 🌟 Push Push — the 'insane pants' (20 Nguyễn Văn Nguyễn)",
          "shop| 🌟 Spot Hideout — archive grails: Issey, Dries, Helmut Lang (158 Trần Quang Khải)",
          "shop| 🌟 Deeritage — curated vintage jewellery (18/4 Trần Quý Khoách)",
          "shop| Untilfaded & Đầu Hàng — more vintage, same neighbourhood; Coromhot for Chrome-Hearts style",
        ]},
        { h: "Evening", items: [
          "? Golden Dragon Water Puppets — 50-min show by City Hall (~17:00 / 18:30), if you skipped Hanoi. Book ahead.",
          "🌟 Ănăn Saigon — ✅ BOOKED, 20:30 (Saigon Tasting Menu + wine pairing). Chef Peter Cuong Franklin's Michelin-starred street-food-turned-haute cuisine, above Chợ Cũ market (89 Tôn Thất Đạm). The trip's one big fine-dining night.",
          "Cocktails after — The Enigma Mansion (Asia's 50 Best Bars), near Ben Thanh (STIR's booked for tomorrow night)",
        ]},
      ],
      stay: "ANIMA Boutique Hotel",
      foot: [
        "Cu Chi Tunnels dropped — you didn't want the crawl or the shooting range, and War Remnants + Reunification (Day 11) cover the war history. That frees this whole day for shopping.",
        "Two walkable clusters: streetwear/designer + the famous pho by Ben Thanh, then the Tân Định vintage loop. Most shops open ~10:00 (The Idiot 13:00, Spot Hideout 12:00) — a relaxed late-morning start works. All indoor, so rain-proof.",
      ] },

    { n: 11, title: "HCMC — History Core & Final Beer 🍺", date: "Wed 1 Jul", iso: "2026-07-01", city: "hcmc",
      tags: [["History","lilac"],["Shopping","lemon"]],
      cols: [
        { h: "Morning — Civic Core (walkable loop)", items: [
          "🌟 War Remnants Museum — go ~08:00 to beat the 12:00–13:30 lunch closure; essential & powerful (28 Võ Văn Tần)",
          "⭐ Reunification Palace — the 1975 tank-through-the-gates site; war rooms & basement bunker (~2 min away, ~40k VND)",
          "see| Notre-Dame Cathedral (exterior — renovation till 2027) + Central Post Office — go inside the post office, that's the highlight",
          "Đồng Khởi + Nguyễn Huệ Boulevard — the main promenade, cafés, browsing",
        ]},
        { h: "Afternoon — Shopping (D3 / Phú Nhuận)", items: [
          "🌟 Lunch — Cơm Tấm Ba Ghiền: Saigon's signature broken rice + charcoal pork chop, Michelin Bib Gourmand, right by the Phú Nhuận shops (84 Đặng Văn Ngữ)",
          "shop| ⭐ 11 Garmentory — two-floor concept boutique + upstairs coffee bar (117B Nguyễn Đình Chính, Phú Nhuận)",
          "shop| Hardy Boys & Whose Studios — basics, denim & hoodies, next-door on Lê Văn Sỹ",
          "shop| Wardrobe Arc & AASTU — more District 3 streetwear nearby",
          "? A+C Coffee — hidden specialty coffee to recharge mid-shop",
        ]},
        { h: "Evening", items: [
          "Relaxed final-night dinner — keep it casual after Ănăn: a Saigon bánh mì / street food, or bar bites at the brewery",
          "🌟 STIR — BOOKED 8pm: Vietnamese-ingredient cocktails (Asia's 50 Best #61) in a colonial alley near Ben Thanh (136 Lê Thánh Tôn)",
          "🍺 ★ Pasteur Street Brewing Company — the last beer of the trip, after STIR",
        ]},
      ],
      stay: "ANIMA Boutique Hotel",
      foot: [
        "War Remnants closes 12:00–13:30 for lunch (open 07:30–17:00 daily) — the early start clears it, and the whole morning loop is walkable.",
        "Afternoon shopping is the Lê Văn Sỹ / Phú Nhuận cluster — ~10 min by Grab from the centre, all close together.",
      ] },

    { n: 12, title: "Last Day — Food Crawl & Departure", date: "Thu 2 Jul", iso: "2026-07-02", city: "hcmc",
      tags: [["Food","blush"],["Shopping","lemon"],["Travel","pink"]],
      cols: [
        { h: "Morning — Steak Breakfast & Cafés", items: [
          "🌟 Bò Né Bà Nũi — the $4 sizzling steak-&-egg breakfast, go first thing (94 Nguyễn Thái Bình)",
          "? Central café / concept loop — 111 Concept Store, Shin Coffee, L'Usine or Mockingbird at the Café Apartment",
          "Check out of ANIMA — store your bags at the hotel (flight's not till 20:00)",
        ]},
        { h: "Afternoon — Last Sweep", items: [
          "Ben Thanh Market — final souvenirs; grab Vietnamese coffee & cashews here, or hit the big Lotte Mart (Q7) for the full haul (~5 km south — its own trip)",
          "? Anything you missed — eyewear (Seeson / Lumla), or a wider run to Aesir in Thảo Điền",
          "One last rooftop / egg coffee before you go",
        ]},
        { h: "Evening — Fly Out", items: [
          "Collect bags → Tân Sơn Nhất Airport by ~17:30",
          "✈️ SGN 20:00 → DOH → JNB 09:35+1 (3 Jul)",
        ]},
      ],
      stay: null,
      foot: ["✈️ Qatar Airways QR 3 · SGN 20:00 → JNB 09:35+1. Flight's at 20:00, so the whole day is yours — store bags after checkout and make it count."] },
  ],

  // ── PLACES (feeds Places grid + map) ──
  // group: shown grouping in Places tab. wishlist:false => map-only.
  // cat: map filter category (coffee|food|shopping|sights|nightlife)
  places: [
    // Cafes & Matcha
    { name: "Cafe Giang", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The original egg coffee since 1946. Must-visit.",
      lat: 21.03335, lng: 105.85155, approx: false },
    { name: "Cafe Đinh", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The other 'original' egg coffee — hidden up a stairwell above a shop at 13 Đinh Tiên Hoàng, with a balcony over Hoan Kiem Lake. More local than Giang.",
      lat: 21.0298, lng: 105.8527, approx: false },
    { name: "The Note Coffee", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Four floors plastered wall-to-wall with handwritten sticky notes since 2012. Egg coffee and coconut frappe. 64 Lương Văn Can, just west of the lake.",
      lat: 21.02995, lng: 105.85155, approx: false },
    { name: "Nagocha Matcha", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Japanese matcha specialty & tea house — ceremonial grades and matcha flights. Flagship two-storey house at 38 Quảng An, West Lake; central branch at B1, 175 Nguyễn Thái Học.",
      lat: 21.0700, lng: 105.8235, approx: true },
    { name: "Artisan Matcha", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Long Biên", desc: "Matcha \"slow bar\" — creative matcha cocktails made tableside, part performance art. Across the river at Ngõ 5 Nguyễn Văn Cừ, Long Biên.",
      lat: 21.0448, lng: 105.871, approx: true },
    { name: "The Matcha Space", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Đống Đa", desc: "Minimalist matcha specialty cafe — single-origin matcha, lattes and desserts. 93B Ngõ 91 Trần Quang Diệu, Đống Đa. Open daily 9:00–22:00.",
      lat: 21.0185, lng: 105.8235, approx: true },
    { name: "Maison de Tết Décor", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Rustic farm-to-table cafe on West Lake — the classic Tây Hồ sunset spot. 26 Quảng Bá. Arrive by ~16:30 for a lakeside table.",
      lat: 21.0760, lng: 105.8205, approx: true },
    { name: "Magicha Zenbar", group: "☕ Cafes & Matcha", cat: "coffee", city: "danang",
      catLabel: "Da Nang — Hải Châu", desc: "Calm matcha-and-zen bar — ceremonial-grade matcha, hojicha & desserts. Flagship at 75/2 Lê Hồng Phong, open 9:00–22:00. (Also a newer Hoi An branch on Tuệ Tĩnh.)",
      lat: 16.0628, lng: 108.2160, approx: true },
    { name: "Reaching Out Teahouse", group: "☕ Cafes & Matcha", cat: "coffee", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Peaceful teahouse in a traditional heritage house in Hoi An Ancient Town, staffed entirely by speech- and hearing-impaired individuals. Premium Vietnamese teas and handmade cookies in a serene garden setting.",
      lat: 15.877, lng: 108.32728, approx: true },
    { name: "43 Factory Coffee Roaster", alias: "43 Factory", group: "☕ Cafes & Matcha", cat: "coffee", city: "danang",
      catLabel: "Da Nang — Ngũ Hành Sơn", desc: "Sprudge-featured specialty roastery with a transparent roasting area and elegant design. One of Vietnam's most serious coffee destinations — in-house roasting, pour-overs, and espresso.",
      lat: 16.0405, lng: 108.2455, approx: true },

    // Food & Drink
    { name: "Ta Hien & Nguyen Trung Truc Streets", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Bun cha, banh cuon, grilled corn — eat everything you see on these food streets.",
      lat: 21.0345, lng: 105.8525, approx: false },
    { name: "Bia Hoi Corner", group: "🍜 Food & Drink", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "25c draught beer on plastic stools. Local institution at Luong Ngoc Quyen.",
      lat: 21.0344, lng: 105.8516, approx: false },
    { name: "Bún chả Hương Liên", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Hai Bà Trưng", desc: "The 'Obama bun cha' — where Obama & Anthony Bourdain ate in 2016 (the combo is on the menu). Smoky grilled pork & noodles. 24 Lê Văn Hưu.",
      lat: 21.01535, lng: 105.85165, approx: false },
    { name: "Quán Cao Lầu Bà Lê", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "White rose dumplings & cao lầu — made with water from the old Bá Lễ well, near the eastern Old Town.",
      lat: 15.8806, lng: 108.3295, approx: true },
    { name: "Morning Glory Restaurant", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Cao Lau noodles — the signature Hoi An noodle, only properly made here.",
      lat: 15.8769, lng: 108.3270, approx: false },
    { name: "Bò Né Bà Nũi", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "The famous ~$4 sizzling beef-steak-&-egg breakfast (bò né) with pâté & crispy baguette. 94 Nguyễn Thái Bình — go early, it gets busy. Right by the Nguyễn Thái Bình shopping cluster.",
      lat: 10.7690, lng: 106.6980, approx: true },
    { name: "Phở Việt Nam", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Michelin-listed pho — signature phở thố đá (sizzling hot stone bowl), fresh daily noodles. 14 Phạm Hồng Thái, ~₫80–100k. Open very long hours.",
      lat: 10.7700, lng: 106.6940, approx: true },

    // ── Fine dining, Michelin & destination bars (foodie picks) ──
    // Hanoi — street food & classics only (no fine dining here, by choice)
    { name: "Chả Cá Lã Vọng", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Single-dish institution since 1871: turmeric-&-dill catfish grilled at your table, finished with sizzling oil, peanuts and bún. A Hanoi rite of passage — the street (Chả Cá) is named after it. 14 Chả Cá.",
      lat: 21.0344, lng: 105.8493, approx: true },
    { name: "Phở Gia Truyền Bát Đàn", alias: "Phở Gia Truyền", group: "🍜 Food & Drink", cat: "food", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Widely rated the best beef phở in Hanoi — clear, slow-simmered broth, a deliberately tiny menu, and a queue you join with a tray, canteen-style. Mornings only-ish; go early. 49 Bát Đàn.",
      lat: 21.0349, lng: 105.8478, approx: true },
    { name: "Nê Cocktail Bar", group: "🍜 Food & Drink", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Hoàn Kiếm", desc: "The bar that kick-started Hanoi's cocktail scene — famous for the 'Phở Cocktail' built on the spices of the noodle soup, plus drinks using kumquat, chilli and local herbs. Original at 3B Tống Duy Tân; bigger Nê Boong-ke at 12 Cửa Đông.",
      lat: 21.02968, lng: 105.8445, approx: true },
    { name: "Polite & Co", group: "🍜 Food & Drink", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Hoàn Kiếm", desc: "1920s gentlemen's-club speakeasy — dark wood, leather, live jazz and seriously good classics. Signature 'The Street Vendor' bottles Hanoi in a glass. The grown-up alternative to the Ta Hien beer stools. 5B Ngõ Báo Khánh, off the west side of Hoàn Kiếm Lake.",
      lat: 21.03002, lng: 105.85206, approx: true },

    // Hoi An
    { name: "Mango Rooms (Mango Mango)", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Chef Duc Tran's riverfront flagship — bold, colourful contemporary Vietnamese fusion and Hoi An's go-to for a special dinner, with terrace tables over the Thu Bồn and the lantern-lit walking street. Book a river table. On the An Hội riverbank (Nguyễn Phúc Chu), opposite the Old Town — double-check the exact spot on arrival.",
      lat: 15.8766, lng: 108.327, approx: true },
    { name: "Nữ Eatery", group: "🍜 Food & Drink", cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Tiny, much-loved modern-Vietnamese spot in a two-storey house by the Japanese Bridge — short menu of inventive small plates (pork-belly steamed buns, smoked-eggplant salad). Foodies' favourite; arrive early, no reservations. 10A Nguyễn Thị Minh Khai.",
      lat: 15.8773, lng: 108.32551, approx: true },

    // Da Nang
    { name: "La Maison 1888", group: "🍜 Food & Drink", cat: "food", city: "danang",
      catLabel: "Da Nang — Sơn Trà · ⭐ 1 Michelin Star", desc: "Central Vietnam's only Michelin-starred restaurant (2024 & 2025) — refined French haute cuisine in a Bill Bensley-designed Indochine villa at the InterContinental Sơn Trà, with sweeping sea views. The trip's blow-out splurge (~₫6–7.5M pp); book ahead, smart dress.",
      lat: 16.1205, lng: 108.30616, approx: true },
    { name: "Nén Danang", group: "🍜 Food & Drink", cat: "food", city: "danang",
      catLabel: "Da Nang — Ngũ Hành Sơn · ♣ Michelin Green Star", desc: "Vietnam's first Michelin Green Star — Chef Summer Le's storytelling tasting menu built almost entirely from central-Vietnam farmers, foragers and fishers. A genuine destination-dining experience and far better value than its global peers. Reserve ahead.",
      lat: 16.0295, lng: 108.2526, approx: true },
    { name: "Bé Mặn Seafood", alias: "Bé Mặn", group: "🍜 Food & Drink", cat: "food", city: "danang",
      catLabel: "Da Nang — Mân Thái (north beach)", desc: "Always-packed local seafood house at the north end of the beach strip (Lô 8 Võ Nguyên Giáp, Mân Thái) — pick your prawns, clams, snails and fish from the trays out front, eat it grilled/steamed with cold beer. Cheap, fresh, no frills (~10 min north of Chicland).",
      lat: 16.086, lng: 108.247, approx: true },
    { name: "Mì Quảng 1A", group: "🍜 Food & Drink", cat: "food", city: "danang",
      catLabel: "Da Nang — Hải Châu", desc: "Michelin-listed home of mì quảng — Da Nang's signature dish of wide turmeric noodles in a little aromatic broth, with prawn, pork, peanuts, herbs and a crisp rice cracker. The bowl to have in its home town. 5 Hải Phòng.",
      lat: 16.07239, lng: 108.21912, approx: true },
    { name: "Sky36", group: "🍜 Food & Drink", cat: "nightlife", city: "danang",
      catLabel: "Da Nang — Riverfront", desc: "Vietnam's highest rooftop bar, on the 36th floor of the Novotel on the Hàn River — 360° views over the city, the coast and (perfectly placed) the Dragon Bridge. Pricey cocktails, DJ later on. Great pre- or post-bridge-show drink. 36 Bạch Đằng.",
      lat: 16.07731, lng: 108.22353, approx: true },

    // HCMC
    { name: "Noriboi Omakase", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1 · ✅ BOOKED Day 9, 20:00", desc: "Japanese omakase — your Saigon arrival-night dinner. ✅ BOOKED 29 Jun, 20:00 for 2 guests (2 Taki sets), booking name Jaedon Van Schalkwyk.",
      lat: 10.7769, lng: 106.7009, approx: true },
    { name: "Ănăn Saigon", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1 · ⭐ 1 Michelin Star", desc: "Vietnam's most famous fine-dining table — Chef Peter Cuong Franklin reimagines street food as haute cuisine (the legendary $100 'Việt Nam pizza' bánh tráng, foie-gras phở). Above the Chợ Cũ market on Tôn Thất Đạm; cocktail bar Nhậu Nhậu and Pot Au Phở sit in the same building. Book ahead.",
      lat: 10.7708, lng: 106.7038, approx: true },
    { name: "CieL", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — Thảo Điền · ⭐ 1 Michelin Star", desc: "Brand-new 2025 Michelin star — Chef Le Hong Viet's precise, minimalist tasting menu in an intimate rooftop room. Out in Thảo Điền (~25 min across the river from D1), so plan it as a dedicated dinner. Reserve well ahead.",
      lat: 10.803, lng: 106.733, approx: true },
    { name: "Quán Bụi Original", alias: "Quán Bụi", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Polished, mid-range traditional Vietnamese in a leafy colonial-style setting — the reliable 'proper sit-down Vietnamese dinner' in District 1, with a good cocktail list. Ideal arrival-night dinner. 17A Ngô Văn Năm.",
      lat: 10.7808, lng: 106.7048, approx: true },
    { name: "The Refinery", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "French-Vietnamese bistro in a former colonial opium refinery, with a leafy courtyard hidden off Hai Bà Trưng. Relaxed, characterful and a lovely final-night dinner. 74 Hai Bà Trưng.",
      lat: 10.77819, lng: 106.70376, approx: true },
    { name: "Cơm Tấm Ba Ghiền", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — Phú Nhuận · Michelin Bib Gourmand", desc: "Saigon's signature dish done best — cơm tấm (broken rice) topped with a charcoal-grilled marinated pork chop, pickled veg and sweet-sour fish sauce. Bib Gourmand 2024 & 2025, ~3,000 plates a day. Unassuming, cheap, essential. 84 Đặng Văn Ngữ, Phú Nhuận (by the Day-11 shops).",
      lat: 10.7935, lng: 106.6748, approx: true },
    { name: "Spice Canvas", group: "🍜 Food & Drink", cat: "food", city: "hcmc",
      catLabel: "HCMC — District 1 · Dessert Atelier", desc: "Intimate dessert-only atelier hidden inside a charming French villa in Tân Định. Chef-driven tasting menus ('Spellbound', 'Moving') that tell stories through bold flavors and fine-dining presentation. Book ahead via Instagram DM — this is a singular experience, not a casual drop-in.",
      lat: 10.7900, lng: 106.6900, approx: true },
    { name: "The Enigma Mansion", group: "🍜 Food & Drink", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Asia's 50 Best Bars (#93, 2025) — a state-of-the-art cocktail list relocated into an atmospheric historic building. Reservation-style speakeasy; pairs naturally with a STIR visit for a serious cocktail night.",
      lat: 10.7825, lng: 106.7048, approx: true },

    // Shopping
    { name: "Old Quarter Night Market", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Friday to Sunday nights, 6–11pm (busiest 7–10pm). Hang Dao up to Dong Xuan Market — shoes, clothes, streetwear, souvenirs, food stalls.",
      lat: 21.0355, lng: 105.8497, approx: false },
    { name: "Hoi An Night Market", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Every night. Lanterns, street food, souvenirs, best atmosphere in town.",
      lat: 15.8760, lng: 108.3290, approx: false },
    { name: "Izi Tailor & I Love Fashion", alias: "I Love Fashion", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Get measured on day 1, collect on day 3. Custom suits, dresses, leather goods.",
      lat: 15.8790, lng: 108.3285, approx: true },
    { name: "Hoan Bespoke Leather", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Bespoke leather workshop in the Old Town — bags, belts & small goods, ready-made or custom, plus make-your-own DIY sessions. Good spot to browse ready-made leather.",
      lat: 15.8772, lng: 108.3282, approx: true },
    { name: "Ben Thanh Market", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Knock-offs, souvenirs, produce, local snacks. The classic HCMC market.",
      lat: 10.7723, lng: 106.6980, approx: false },
    { name: "The New Playground", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Underground streetwear hub at 26 Lý Tự Trọng — 20+ local brands under one roof. Open 10:00–21:30.",
      lat: 10.7770, lng: 106.6968, approx: false },
    { name: "Rue Miche", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Multi-brand fashion boutique in a restored 1952 French colonial villa. 25+ curated local brands. 9B Phùng Khắc Khoan.",
      lat: 10.787, lng: 106.697, approx: true },
    { name: "Das Studios", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Leading Vietnamese menswear brand — clean contemporary cuts with a sharp eye on tailoring.",
      lat: 10.7625, lng: 106.6895, approx: true },
    { name: "Lider", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Trendy unisex fashion at 7 Tôn Thất Thiệp. Clean cuts, flare jeans, streetwear. Also at The New Playground B2.",
      lat: 10.7732, lng: 106.7035, approx: true },
    { name: "AASTU (AA Flagship Store)", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "American-style Vietnamese menswear at 118/12 Trần Quang Diệu. Clean lines, contemporary cuts, friendly staff.",
      lat: 10.7880, lng: 106.6860, approx: true },
    { name: "Fit Something (FSTH)", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Curated leather shoe shop where the owner actually knows sizing and fit. Dress shoes, loafers, boots — real leather, Vietnamese-made. Personal service, not pushy retail. Call ahead to check stock (size 44+ selection is limited). 256/21C Pasteur.",
      lat: 10.7820, lng: 106.6940, approx: true },
    { name: "Wardrobe Arc", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Retail complex with 20+ local streetwear brands at 351/44 Lê Văn Sỹ. Dark palettes, bold young streetwear. Open 9:30–21:30.",
      lat: 10.7905, lng: 106.6815, approx: true },
    { name: "Aesir Studios", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Thảo Điền", desc: "German-Vietnamese designer streetwear. AE Space at 20 Duong 46, Thao Dien + flagship at 128G Nguyễn Đình Chính.",
      lat: 10.8030, lng: 106.7340, approx: true },
    { name: "Lumla Glasses", alias: "Lumla", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Vietnam's most viral sunglasses store — huge selection of trendy frames at great prices. 51 Lê Thị Riêng, D1.",
      lat: 10.7720, lng: 106.6910, approx: true },
    { name: "Seeson", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Contemporary Vietnamese eyewear — handcrafted acetate frames with an optometry clinic and cafe in-store. Flagship on Nam Kỳ Khởi Nghĩa, D1.",
      lat: 10.776, lng: 106.699, approx: true },
    { name: "Rue Miche L'Édition", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Rue Miche's new flagship retail hub (Aug 2025) — 30+ local designers, plus Rotten Bar and a wellness space. LL3 (B3), Union Square, 171 Đồng Khởi. Open 10:00–21:00.",
      lat: 10.7770, lng: 106.7035, approx: true },
    { name: "Đầu Hàng", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Đa Kao", desc: "\"Home of curated goods\" — vintage garments, statement jewellery and funky housewares. Main store 26/78 Nguyễn Bỉnh Khiêm, Đa Kao. Open 10:00–20:30.",
      lat: 10.7882, lng: 106.7005, approx: true },
    { name: "Untilfaded", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Tân Định", desc: "Vintage & designer finds, sun-dried for months to that perfect faded look. 82/2 Võ Thị Sáu, Tân Định.",
      lat: 10.7905, lng: 106.6895, approx: true },
    { name: "Compound Garment", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Multi-brand local streetwear, unisex, reasonable prices. 158/5 Nguyễn Công Trứ (Nguyễn Thái Bình cluster). ~10:00–21:00.",
      lat: 10.7680, lng: 106.7010, approx: true },
    { name: "Waa Studio", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "In-house designed handbags & leather goods — design-forward flagship. 38 Đặng Thị Nhu, ~5 min from Ben Thanh.",
      lat: 10.7690, lng: 106.7000, approx: true },
    { name: "The Idiot", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Elevated, experimental fashion — gender-neutral, bold silhouettes, statement denim. 62 Nguyễn Thái Bình, daily ~13:00–21:00.",
      lat: 10.7690, lng: 106.6981, approx: true },
    { name: "Push Push", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Tân Định", desc: "Sporty streetwear with a high-fashion edge — the 'insane pants' spot. 20 Nguyễn Văn Nguyễn, Tân Định, ~09:30–21:30. (Check @push___push for pop-up locations.)",
      lat: 10.7900, lng: 106.6900, approx: true },
    { name: "Deeritage", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Tân Định", desc: "Owner-curated vintage jewellery, secondhand watches & décor — 'no junk.' 18/4 Trần Quý Khoách, Tân Định, ~10:00–22:00.",
      lat: 10.7910, lng: 106.6902, approx: true },
    { name: "Spot Hideout", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Tân Định", desc: "Serious archive/vintage store — Issey Miyake, Dries, JPG, Helmut Lang, workwear. 158 Trần Quang Khải, Tân Định, ~12:00–20:00. For collectors (not cheap).",
      lat: 10.7920, lng: 106.6890, approx: true },
    { name: "11 Garmentory", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Phú Nhuận", desc: "Two-storey multi-brand concept boutique (local designers + streetwear) with an upstairs coffee bar. 117B Nguyễn Đình Chính, Phú Nhuận, ~10:00–21:30.",
      lat: 10.7990, lng: 106.6770, approx: true },
    { name: "Hardy Boys", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Minimalist versatile basics & affordable denim, two floors. 386/7 Lê Văn Sỹ (next to Whose Studios), ~10:00–22:00.",
      lat: 10.7930, lng: 106.6810, approx: true },
    { name: "Whose Studios", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Affordable oversized hoodies & jackets (~$20), polos, tees. 386/15 Lê Văn Sỹ, next door to Hardy Boys.",
      lat: 10.7931, lng: 106.6812, approx: true },
    { name: "111 Concept Store", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Local-designer goods, art, stickers, handmade gifts & souvenirs. 111 Tôn Thất Đạm, Bến Nghé.",
      lat: 10.7710, lng: 106.7040, approx: true },
    { name: "Lotte Mart (Q7)", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 7", desc: "Big, well-stocked branch for the souvenir run — Vietnamese coffee, cashews, dried fruit, snacks. 469 Nguyễn Hữu Thọ, ~07:30–22:00. ~5 km south — a standalone errand.",
      lat: 10.74105, lng: 106.70223, approx: true },
    { name: "Metiseko", group: "🛍️ Shopping", cat: "shopping", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Eco-conscious fashion and homeware brand at 140 Trần Phú. Organic cotton and mulberry silk clothing, accessories, and homewares — all made sustainably in Vietnam. A world away from the mass-market silk stalls.",
      lat: 15.8776, lng: 108.3266, approx: true },
    { name: "Zó Project", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Social enterprise preserving 800-year-old Vietnamese Dó paper. Handcrafted notebooks, postcards, and art supplies in a small shop near West Lake. Featured in the New York Times and BBC.",
      lat: 21.0479, lng: 105.8115, approx: true },
    { name: "Zaker Store", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Branded fashion outlet on Hàng Bông — international labels (Nike, Adidas, The North Face, Puma and more) at export/overrun prices. A proper hunt-through-racks spot. 201 Hàng Bông, open 8:00–22:00.",
      lat: 21.0312, lng: 105.8478, approx: true },
    { name: "The Raw Compound", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Đống Đa", desc: "Concept space with 20+ local streetwear brands under one roof — Hanoi's best one-stop for homegrown labels. 180 La Thành.",
      lat: 21.0190, lng: 105.8190, approx: true },
    { name: "Hang Gai Street", group: "🛍️ Shopping", cat: "shopping", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The silk street — tailors, silk, lacquerware and art galleries, a short walk NW of Hoan Kiem Lake.",
      lat: 21.0323, lng: 105.8502, approx: true },

    // Things to Do
    { name: "Tran Quoc Pagoda", group: "🎯 Things to Do", cat: "sights", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Hanoi's oldest pagoda (6th century) on a tiny islet in West Lake — best at sunset. Easy add-on if you're heading to Nagocha at Tây Hồ.",
      lat: 21.0490, lng: 105.8377, approx: false },
    { name: "Phu Tay Ho", group: "🎯 Things to Do", cat: "sights", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "Lakeside temple on the Quảng An peninsula, ~400 m from Nagocha — with a food street famous for bánh tôm (shrimp cakes) and bún ốc.",
      lat: 21.0722, lng: 105.8232, approx: true },
    { name: "My Son Sanctuary", group: "🎯 Things to Do", cat: "sights", city: "hoian",
      catLabel: "Hoi An — My Son (~40 km W)", desc: "The Champa kingdom's royal temple-capital — clusters of 4th–14th c. Hindu brick towers in a jungle valley. Go early (heat + crowds). UNESCO.",
      lat: 15.76878, lng: 108.11932, approx: false },
    { name: "An Bang Beach", group: "🎯 Things to Do", cat: "sights", city: "hoian",
      catLabel: "Hoi An — An Bang", desc: "Hoi An's best beach (~15 min from town) — loungers, beach bars (Soul Kitchen, La Plage), fresh seafood. A cooling afternoon escape.",
      lat: 15.917, lng: 108.3395, approx: false },
    { name: "Museum of Cham Sculpture", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Hai Chau", desc: "World's best Champa collection — the sandstone sculptures pulled from My Son's towers. Open daily, AC, a great midday heat-break. 2 Tháng 9 St.",
      lat: 16.05989, lng: 108.22264, approx: false },
    { name: "Ba Na Hills + Golden Bridge", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Ba Na Hills", desc: "World's longest cable car, giant stone hands (Golden Bridge), French Village. Go early (cable car from ~08:00) to beat crowds & fog. Book online (~900k VND pp).",
      lat: 15.9950, lng: 107.9960, approx: false },
    { name: "My Khe Beach", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — My Khe", desc: "Steps from Chicland. Sunrise swim, seafood on the sand.",
      lat: 16.0544, lng: 108.2470, approx: false },
    { name: "Dragon Bridge 🐉", group: "🎯 Things to Do", cat: "sights", city: "danang",
      catLabel: "Da Nang — Riverfront", desc: "Fire & water show Friday, Saturday & Sunday at 21:00. You're there for both weekend nights!",
      lat: 16.0614, lng: 108.2275, approx: false },
    { name: "An Thuong Street + Mango Archive", group: "🎯 Things to Do", cat: "shopping", city: "danang",
      catLabel: "Da Nang — An Thuong", desc: "Full vintage strip with Mango Archive (your pick), Rust Rack, Hana 34, ORI jewellery. Afternoon stroll near the beachfront.",
      lat: 16.04, lng: 108.245, approx: true },
    { name: "War Remnants Museum", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Essential and powerful. Open daily 07:30–17:00 with a 12:00–13:30 lunch closure — go ~08:00. 28 Võ Văn Tần.",
      lat: 10.7795, lng: 106.6917, approx: false },
    { name: "Reunification Palace", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "The 1975 \"tank through the gates\" site — the preserved 1960s presidential palace with war rooms, basement bunker & period interiors. 135 Nam Kỳ Khởi Nghĩa, ~2 min walk from War Remnants. Open daily ~08:00–16:30, ~40k VND.",
      lat: 10.7772, lng: 106.6958, approx: false },
    { name: "Golden Dragon Water Puppets", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "HCMC's main water-puppet theatre — 50-min show, ~17:00 / 18:30 / 19:45. 55B Nguyễn Thị Minh Khai, by City Hall. Book ahead. The Saigon stand-in if you skip the Hanoi puppets.",
      lat: 10.7762, lng: 106.6923, approx: true },
    { name: "Cu Chi Tunnels", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — Day Trip", desc: "Half-day tour. Crawl the tunnel network, shooting range optional (~60k VND).",
      lat: 11.0566, lng: 106.5223, approx: false },
    { name: "Bui Vien Walking Street", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Food, drinks, backpacker energy. Nightlife central.",
      lat: 10.7670, lng: 106.6920, approx: false },
    { name: "Saigon River Rooftop Bars", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — Riverfront", desc: "Skyline views over the river. Perfect for the last night.",
      lat: 10.7720, lng: 106.7050, approx: true },
    { name: "Workshop14", group: "🎯 Things to Do", cat: "nightlife", city: "hanoi",
      catLabel: "Hanoi — Tây Hồ", desc: "Hidden speakeasy cocktail bar in Tây Hồ district, set in a former architect's studio on the site of a 12th-century royal palace. Asia's 50 Best Bars 2025 (#83). Stripped-back concrete design with skylights, natural materials, and serene lighting.",
      lat: 21.0668, lng: 105.821, approx: true },
    { name: "STIR — Modern Classic Cocktail", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "First-floor speakeasy in a colonial-era alleyway near Ben Thanh Market. Asia's 50 Best Bars mainstay (#61 in 2025). Vietnamese-ingredient cocktails like 'Xôi Mít' (jackfruit, jasmine, sticky rice, peated Scotch) alongside faithful classics.",
      lat: 10.7730, lng: 106.6970, approx: true },

    // ── map-only landmarks (wishlist:false) ──
    { name: "Hoan Kiem Lake & Ngoc Son Temple", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "The heart of the Old Quarter — lake, red bridge, island temple. Temple 8:00–18:00.",
      lat: 21.0287, lng: 105.8524, approx: false },
    { name: "Hoa Lo Prison", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Hoan Kiem", desc: "The \"Hanoi Hilton\" — gripping, well-curated museum. Open daily 8:00–17:00.",
      lat: 21.0254, lng: 105.8466, approx: false },
    { name: "Temple of Literature", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi", desc: "Vietnam's oldest university (1070).",
      lat: 21.0273, lng: 105.8355, approx: false },
    { name: "Ho Chi Minh Mausoleum & Museum", alias: "Ba Dinh", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Ba Dinh", desc: "Mausoleum, museum, One Pillar Pagoda. Mausoleum closed Mondays.",
      lat: 21.0368, lng: 105.8350, approx: false },
    { name: "Train Street", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi", desc: "Trains pass inches from the cafes. Check current access rules.",
      lat: 21.0276, lng: 105.8491, approx: false },
    { name: "Thang Long Water Puppet Theatre", alias: "Thang Long", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Old Quarter", desc: "Traditional water puppetry, ~1 hr. Book ahead.",
      lat: 21.0294, lng: 105.8538, approx: false },
    { name: "Trung Trang Cave", group: "_map", wishlist: false, cat: "sights", city: "halong",
      catLabel: "Lan Ha Bay — Cat Ba", desc: "Stalactite cavern in Cat Ba National Park (~300 m through-tunnel) — the Mon Cheri cruise's actual cave stop, reached via the Gia Luan jetty.",
      lat: 20.7930, lng: 106.9980, approx: true },
    { name: "Tuan Chau Marina", group: "_map", wishlist: false, cat: "sights", city: "halong",
      catLabel: "Ha Long — Tuan Chau Island", desc: "Cruise embarkation/disembarkation port on Tuan Chau Island, SW Ha Long. Board ~12:00, disembark ~11:00.",
      lat: 20.9133, lng: 106.9847, approx: true },
    { name: "Tra Bau", group: "_map", wishlist: false, cat: "sights", city: "halong",
      catLabel: "Lan Ha Bay", desc: "Sheltered area in mid-Lan Ha Bay — the ~15:30 kayaking & swimming stop, with a floating fishing village and hidden lagoons.",
      lat: 20.7800, lng: 107.0650, approx: true },
    { name: "Banh Mi Phuong", group: "_map", wishlist: false, cat: "food", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Famous banh mi — Anthony Bourdain's pick. Breakfast go-to.",
      lat: 15.87843, lng: 108.33207, approx: false },
    { name: "Phuc Kien Assembly Hall", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Ornate Fujian temple with hanging incense spirals.",
      lat: 15.87748, lng: 108.33063, approx: false },
    { name: "Japanese Covered Bridge", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "The 18th-century icon of Hoi An.",
      lat: 15.8770, lng: 108.3258, approx: false },
    { name: "Cam Thanh Coconut Village", group: "_map", wishlist: false, cat: "sights", city: "hoian",
      catLabel: "Hoi An", desc: "Basket boat rides through the water-coconut palms.",
      lat: 15.8920, lng: 108.3640, approx: true },
    { name: "Marble Mountains", group: "_map", wishlist: false, cat: "sights", city: "danang",
      catLabel: "Da Nang", desc: "Five limestone hills with Buddhist cave temples. Go before 10am.",
      lat: 16.0036, lng: 108.2630, approx: false },
    { name: "Lady Buddha (Linh Ung Pagoda)", group: "_map", wishlist: false, cat: "sights", city: "danang",
      catLabel: "Da Nang — Son Tra", desc: "67m white statue on the Son Tra Peninsula. Monkeys about.",
      lat: 16.1003, lng: 108.2780, approx: false },
    { name: "Notre-Dame Cathedral & Post Office", group: "_map", wishlist: false, cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Exterior only — under renovation until 2027.",
      lat: 10.7797, lng: 106.6990, approx: false },
    { name: "Nguyen Hue Boulevard", group: "_map", wishlist: false, cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Pedestrian promenade, cafes, the walking street's heart.",
      lat: 10.7740, lng: 106.7040, approx: false },
    { name: "Pasteur Street Brewing Co.", group: "_map", wishlist: false, cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "HCMC's best craft brewery — the final beer. 144 Pasteur.",
      lat: 10.77518, lng: 106.70103, approx: true },

    // ── added from the independent map audit ──
    { name: "C'est Bon Café", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — West Lake", desc: "White-villa garden cafe at 5 Tây Hồ St, Quảng An — the alternate West Lake sunset spot to Maison de Tết Décor.",
      lat: 21.0671, lng: 105.8194, approx: true },
    { name: "Long Bien Bridge", group: "_map", wishlist: false, cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Red River", desc: "Historic Doumer-era cantilever bridge over the Red River — the free Train Street fallback, walkable for views.",
      lat: 21.0418, lng: 105.8556, approx: true },
    { name: "Soul Kitchen", group: "🎯 Things to Do", cat: "nightlife", city: "hoian",
      catLabel: "Hoi An — An Bang Beach", desc: "The most popular An Bang beach bar — live music Thu–Sun, sunset drinks, beachfront dining. 142 Nguyễn Phan Vinh.",
      lat: 15.9172, lng: 108.3396, approx: true },
    { name: "La Plage", group: "🎯 Things to Do", cat: "nightlife", city: "hoian",
      catLabel: "Hoi An — An Bang Beach", desc: "Relaxed beachfront bar-restaurant on An Bang, just south of Soul Kitchen — sunset drinks & French-leaning menu.",
      lat: 15.9156, lng: 108.3392, approx: true },
    { name: "Son Tra Night Market", group: "🎯 Things to Do", cat: "nightlife", city: "danang",
      catLabel: "Da Nang — Han Riverfront", desc: "Riverside night market on Mai Hắc Đế / Lý Nam Đế, ~200 m east of the Dragon Bridge — food, souvenirs, ~17:00–22:30.",
      lat: 16.06159, lng: 108.23198, approx: true },
    { name: "Boulevard Gelato", group: "☕ Cafes & Matcha", cat: "coffee", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Gelato, pastry & coffee pit-stop in the Nguyễn Thái Bình cluster. 25 Hồ Tùng Mậu.",
      lat: 10.7700, lng: 106.7040, approx: true },
    { name: "Coromhot", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — Đa Kao", desc: "Chrome-Hearts-style silver jewellery & archive pieces (buy/sell). 93 Mai Thị Lựu, Đa Kao.",
      lat: 10.7890, lng: 106.6970, approx: true },
    { name: "The Café Apartment", group: "☕ Cafes & Matcha", cat: "coffee", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "The iconic café-and-shop block at 42 Nguyễn Huệ — Mockingbird and dozens of cafés/boutiques stacked floor by floor.",
      lat: 10.7740, lng: 106.7040, approx: true },
    { name: "Shin Coffee", group: "☕ Cafes & Matcha", cat: "coffee", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Serious Vietnamese specialty coffee. 13 Nguyễn Thiệp, Bến Nghé.",
      lat: 10.7745, lng: 106.70425, approx: true },
    { name: "L'Usine", group: "☕ Cafes & Matcha", cat: "coffee", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Café + concept/fashion store — brunch, coffee & lifestyle retail. 151 Đồng Khởi (also 70B Lê Lợi).",
      lat: 10.7760, lng: 106.7030, approx: true },
    { name: "A+C Coffee", group: "☕ Cafes & Matcha", cat: "coffee", city: "hcmc",
      catLabel: "HCMC — District 3", desc: "Hidden specialty coffee in an alley off Pasteur. 230/18 Pasteur, Võ Thị Sáu.",
      lat: 10.7850, lng: 106.6900, approx: true },
    { name: "EON Heli Bar", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — Bitexco Tower", desc: "Rooftop bar on L52 of Bitexco Financial Tower — skyline & river views. 2 Hải Triều.",
      lat: 10.7717, lng: 106.7045, approx: true },
    { name: "Chill Sky Bar", group: "🎯 Things to Do", cat: "nightlife", city: "hcmc",
      catLabel: "HCMC — AB Tower", desc: "Open-air rooftop bar on the AB Tower — city panorama, cocktails. 76A Lê Lai, Bến Thành.",
      lat: 10.7707, lng: 106.6927, approx: true },
    { name: "The Craftsman Cocktail Bar", group: "🎯 Things to Do", cat: "nightlife", city: "danang",
      catLabel: "Da Nang — Yên Bái", desc: "Proper speakeasy hidden in a century-old house on Yên Bái — enter through a secret door to find a dim, craft-forward cocktail bar. Live music on Wednesdays and Saturdays. The menu is short and focused, and the vibe is intimate, not touristy.",
      lat: 16.0610, lng: 108.2270, approx: true },
    { name: "Lighthouse Coffee Roaster", group: "☕ Cafes & Matcha", cat: "coffee", city: "danang",
      catLabel: "Da Nang — Sơn Trà", desc: "Warehouse-style specialty roaster in a striking brick building with open floors and industrial design. Serious coffee (in-house roasting, pour-overs, cold brew) in a space that feels like Da Nang's answer to a Berlin roastery. 12 Đình Nghệ, Sơn Trà.",
      lat: 16.0600, lng: 108.2480, approx: true },
    { name: "The Espresso Station", group: "☕ Cafes & Matcha", cat: "coffee", city: "hoian",
      catLabel: "Hoi An — Ancient Town", desc: "Hidden alley specialty coffee roastery — widely credited as the first to bring serious third-wave coffee to Hoi An. Charcoal-roasted beans, premium Vietnamese single origins, and a tiny, unmarked space that feels like a secret. The definition of singular excellence in a town full of tourist coffee.",
      lat: 15.8770, lng: 108.3280, approx: true },
    { name: "Mo Art Space", group: "🎯 Things to Do", cat: "sights", city: "hanoi",
      catLabel: "Hanoi — Hoàn Kiếm", desc: "Contemporary art gallery in a heritage shophouse basement on Hàng Trống. Free admission, rotating exhibitions of Vietnamese and international artists. A quiet, curated culture stop in the Old Quarter — far from the lanyard crowd.",
      lat: 21.0300, lng: 105.8520, approx: true },
    { name: "Gom Saigon", group: "🛍️ Shopping", cat: "shopping", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "Hidden ceramics studio and matcha cafe on the second floor of 42 Nguyễn Huệ (near the Café Apartments). Hand-build pottery amid greenery and shelves of finished pieces, then sip matcha downstairs. Book the workshop via DM — a slow, hands-on afternoon in the heart of the city.",
      lat: 10.7740, lng: 106.7040, approx: true },
    { name: "Loading T Cafe", group: "☕ Cafes & Matcha", cat: "coffee", city: "hanoi",
      catLabel: "Hanoi — Hoàn Kiếm", desc: "Hidden second-floor cafe in a 120-year-old French colonial shophouse on Chân Cầm, right in the Old Quarter. Vintage atmosphere, comfortable seating, and some of the best egg coffee in Hanoi. The kind of quiet, considered space that rewards the hunt.",
      lat: 21.0315, lng: 105.8525, approx: true },
    { name: "Black Wolf Bespoke Cocktail Bar", group: "🎯 Things to Do", cat: "nightlife", city: "danang",
      catLabel: "Da Nang — Sơn Trà", desc: "Tiny, beautifully designed speakeasy-style bar in Sơn Trà where there is no menu — you describe your taste and the bartender builds a bespoke cocktail around it. Intimate, non-touristy, and the definition of singular excellence.",
      lat: 16.0600, lng: 108.2480, approx: true },
    { name: "L'Apothiquaire Spa", group: "🎯 Things to Do", cat: "sights", city: "hcmc",
      catLabel: "HCMC — District 1", desc: "A French-Vietnamese day spa with genuine design pedigree — the original branch is a tranquil sanctuary in the heart of downtown, with bespoke treatments, natural ingredients, and a perfumery. The antithesis of a hotel-chain spa.",
      lat: 10.7730, lng: 106.7000, approx: true },
  ],

  // ── PACKING ──
  packing: [
    { label: "Passports (valid 6+ months)" },
    { label: "E-visa approved", checked: true },
    { label: "Travel insurance purchased" },
    { label: "Flights booked — Qatar QR 8MXDM6", checked: true },
    { label: "Accommodation — all 5 stays booked", checked: true },
    { label: "Mon Cheri Cruises booked", checked: true },
    { label: "Copies of docs (digital + printed)" },
    { label: "Notify bank of travel" },
    { label: "Cash (VND) + card with no FX fees" },
    { label: "Light clothing — tropical weight" },
    { label: "Rain jacket / umbrella" },
    { label: "Swimwear" },
    { label: "Good walking shoes" },
    { label: "Insect repellent" },
    { label: "Sunscreen" },
    { label: "Power adapter (2-pin round)" },
    { label: "Portable charger" },
    { label: "Reusable water bottle" },
    { label: "Basic medicine kit" },
    { label: "Earplugs + eye mask" },
    { label: "Daypack for excursions" },
  ],

  // ── CURRENCY (live rate fetched at runtime; this is the offline fallback) ──
  currency: {
    base: "ZAR", quote: "VND",
    fallbackRate: 1450,            // ~1 ZAR in VND (approx, offline fallback)
    // quick amounts shown on the cheat-sheet (in VND)
    cheats: [20000, 50000, 100000, 200000, 500000, 1000000],
  },

  // ── VIETNAMESE PHRASES (offline) ──
  phrases: [
    { g: "Essentials", items: [
      ["Hello", "Xin chào", "sin chow"],
      ["Thank you", "Cảm ơn", "gam un"],
      ["Yes / No", "Vâng / Không", "vung / khom"],
      ["Sorry / Excuse me", "Xin lỗi", "sin loy"],
      ["I don't understand", "Tôi không hiểu", "toy khom hyoo"],
      ["Do you speak English?", "Bạn nói tiếng Anh không?", "ban noy tyeng anh khom"],
    ]},
    { g: "Eating & drinking", items: [
      ["The bill, please", "Tính tiền", "ting tyen"],
      ["Delicious!", "Ngon quá", "ngon kwa"],
      ["No ice", "Không đá", "khom da"],
      ["Not spicy", "Không cay", "khom kai"],
      ["Vegetarian", "Ăn chay", "an chai"],
      ["Cheers!", "Một, hai, ba, dô!", "mot hai ba yo"],
    ]},
    { g: "Shopping & getting around", items: [
      ["How much?", "Bao nhiêu tiền?", "bow nyew tyen"],
      ["Too expensive", "Đắt quá", "dat kwa"],
      ["Where is…?", "…ở đâu?", "uh dow"],
      ["Stop here", "Dừng ở đây", "zung uh day"],
      ["Toilet", "Nhà vệ sinh", "nya ve sing"],
    ]},
    { g: "Numbers", items: [
      ["1 / 2 / 3", "một / hai / ba", "mot / hai / ba"],
      ["4 / 5 / 6", "bốn / năm / sáu", "bon / nam / sow"],
      ["7 / 8 / 9", "bảy / tám / chín", "bai / tam / chin"],
      ["10 / 100 / 1000", "mười / trăm / nghìn", "muoi / cham / ngin"],
    ]},
    { g: "Emergency words", items: [
      ["Help!", "Cứu tôi!", "gew toy"],
      ["Hospital", "Bệnh viện", "ben vyen"],
      ["Doctor", "Bác sĩ", "bak see"],
      ["Police", "Công an", "kom an"],
    ]},
  ],

  // ── EMERGENCY (offline) ──
  emergency: {
    numbers: [
      { label: "Police", num: "113", icon: "🚓" },
      { label: "Ambulance", num: "115", icon: "🚑" },
      { label: "Fire", num: "114", icon: "🚒" },
    ],
    notes: [
      { label: "SA Embassy, Hanoi", detail: "31 Hai Bà Trưng, Hoàn Kiếm, Hanoi", tel: "+842439362000", verify: true },
      { label: "SA Consulate, HCMC", detail: "Saigon Tower, 29 Lê Duẩn, District 1", tel: "+842838235945", verify: true },
    ],
    tip: "Save these offline. For a taxi, show the driver your hotel from the Stays list — tap any stay for its pin and Vietnamese area name.",
  },
};
